import io
D = "/sessions/lucid-funny-planck/mnt/outputs/"
F = D + "cyber-briefing.html"
s = io.open(F, encoding="utf-8").read()
n = 0
def rep(old, new):
    global s, n
    assert s.count(old) == 1, "MISS(%d): %s" % (s.count(old), old[:90])
    s = s.replace(old, new); n += 1

# ---- 1. TLDR ----
rep("while two CISA remediation deadlines for actively exploited flaws, including a CVSS 10.0 Cisco firewall bug used by both a ransomware crew and a Sandworm-linked state actor, expire today.</span></div>",
    "while three CISA remediation deadlines for actively exploited flaws &mdash; among them a CVSS 10.0 Cisco firewall bug used by both a ransomware crew and a Sandworm-linked state actor &mdash; expire today, and a newly surfaced fourth KEV batch puts two exploited Windows privilege-escalation zero-days on a 22 September clock.</span></div>")

# ---- 2. Threat banner ----
rep("<span class=\"wy\">Two federal remediation deadlines for actively exploited vulnerabilities expire <b>today</b>, one of them a <b>CVSS 10.0</b> pre-authentication root flaw in a security appliance that has already been used to deploy ransomware and Russian state malware.</span>",
    "<span class=\"wy\">Three federal remediation deadlines for actively exploited vulnerabilities expire <b>today</b>, one of them a <b>CVSS 10.0</b> pre-authentication root flaw in a security appliance already used to deploy ransomware and Russian state malware &mdash; and two Windows zero-days exploited before a patch existed are now on a <b>22 September</b> federal clock.</span>")

# ---- 3. Stat strip ----
rep("<div class=\"stat\"><div class=\"n critc\">0</div><div class=\"l\">Days left on two CISA KEV deadlines</div></div><div class=\"stat\"><div class=\"n\">966</div><div class=\"l\">Flaws in September Patch Tuesday on BleepingComputer&rsquo;s count, incl. 2 zero-days — other tallies give 964 and 973</div></div>",
    "<div class=\"stat\"><div class=\"n critc\">0</div><div class=\"l\">Days left on three CISA KEV deadlines</div></div><div class=\"stat\"><div class=\"n\">966&ndash;997</div><div class=\"l\">Flaws in September Patch Tuesday &mdash; a sourced range, not a disagreement; the spread depends on how external and Chromium bugs are counted</div></div>")

# ---- 4. Patch Priority: mention the companion deadlines ----
rep("<b>Critical caveat:</b> the hot fixes prevent future exploitation but <b>do not remediate an existing compromise</b> — patching is not sufficient; assume breach and hunt for the indicators below.</p></div>",
    "<b>Critical caveat:</b> the hot fixes prevent future exploitation but <b>do not remediate an existing compromise</b> &mdash; patching is not sufficient; assume breach and hunt for the indicators below. The 12 September deadline is <b>re-confirmed this run</b> against the same-day reporting of CISA&rsquo;s bulletin, which names the Cisco, Citrix and Fortinet flaws together under it.</p></div>")

# ---- 5. New breach/incident cards ----
rep("<div class=\"card\"><span class=\"chip\">Carried</span><span class=\"chip hot\">Supply chain</span><h3>Trezor / ShipMonk — 81,000 customers</h3>",
    "<div class=\"card\"><span class=\"chip new\">New</span><span class=\"chip hot\">Pre-exploitation warning</span><h3>Dutch NCSC warns of imminent exploitation of two Check Point VPN flaws</h3><p>On <b>11 September</b> the Netherlands&rsquo; <b>Nationaal Cyber Security Centrum</b> warned of <b>imminent</b> exploitation of two critical Check Point VPN vulnerabilities, <b>CVE-2026-85102</b> and <b>CVE-2026-85103</b>, either of which can be used for remote code execution. This is a warning about expected exploitation rather than a report of it, and it is published as such &mdash; neither CVE appeared in any KEV batch read this run, and no CVSS figure for either was stated in the sources read, so none is given in the table below.</p></div><div class=\"card\"><span class=\"chip new\">New</span><span class=\"chip warn\">Single-source</span><h3>&ldquo;ShieldCrash&rdquo; &mdash; a Defender zero-day published the day after Patch Tuesday</h3><p>An anonymous researcher using the handle <b>Nightmare Eclipse</b> is reported to have released a new <b>Microsoft Defender</b> zero-day exploit named <b>ShieldCrash</b> immediately after Microsoft shipped its September Patch Tuesday updates. <b>Graded deliberately low:</b> this rests on a single search result this run and no vendor advisory, CVE identifier or independent confirmation was obtained, so no severity, affected version or impact is asserted here. It is included because a publicly released exploit against endpoint security software is worth knowing about even at this evidentiary weight &mdash; and excluded from the table below for the same reason.</p></div><div class=\"card\"><span class=\"chip\">Carried</span><span class=\"chip hot\">Supply chain</span><h3>Trezor / ShipMonk — 81,000 customers</h3>")

# ---- 6. Refusals panel, after the breach cards ----
rep("<h2>Vulnerability Watch</h2>",
    "<h2>Refused This Run</h2><div class=\"callout\" style=\"border-left-color:var(--warn)\"><b>Three items were read and are not published &mdash; here is why</b><p style=\"margin:0 0 9px;font-size:15px;color:#c6ced6\"><b>1. Summit Pathology, 1,813,538 patients &mdash; a 2024 breach resurfacing as though it were today&rsquo;s news.</b> A general search for current breach reporting returned this as a live item. It is not. Following it to source: the intrusion was <b>detected on 18 April 2024</b>, Summit Pathology and Summit Pathology Laboratories <b>notified HHS on 18 October</b> of that year, and litigation was filed <b>within 48 hours</b> of the patient notice &mdash; all of it 2024 coverage. The <b>Medusa</b> ransomware group is <i>suspected</i>, which is a further reason not to promote it. The figure is accurate and the story is real; it is simply two years old, and publishing it in a briefing dated today would be the single most misleading thing on this page.</p><p style=\"margin:0;font-size:15px;color:#c6ced6\"><b>2 and 3. Imperial Healthcare Solutions and DiamondLease &mdash; leak-site listings and nothing else.</b> Both were named on ransomware data-leak sites dated <b>12 September</b>, DiamondLease on <b>NightSpire</b>, with the groups claiming stolen internal data. In neither case is there a victim statement, a regulator filing, a record count or any independent corroboration in the sources read this run. Imperial Healthcare Solutions was refused on identical grounds in a previous edition and is refused again. <b>An extortion group&rsquo;s own claim that it has your data is an advertisement, not a disclosure.</b></p></div>\n\n<h2>Vulnerability Watch</h2>")

# ---- 7. New CVE rows ----
rep("<tr><td><b>CVE-2026-72898</b></td>",
    "<tr><td><b>CVE-2026-85880</b></td><td class=\"warnc\">7.8</td><td>Microsoft Windows &mdash; Advanced Local Procedure Call (ALPC)</td><td>Heap-based buffer overflow; a local attacker escalates to <b>SYSTEM</b>. Low privileges required, low attack complexity, no user interaction &mdash; and <b>confirmed exploited before a patch existed</b>. Fixed in the <b>8 September</b> Patch Tuesday. KEV <b>8 Sept</b>, due <b>22 Sept</b>.</td></tr><tr><td><b>CVE-2026-81963</b></td><td class=\"warnc\">7.8</td><td>Microsoft Windows &mdash; Windows Update Stack</td><td>Improper link resolution before file access (link following); local escalation to <b>SYSTEM</b>. The second of September&rsquo;s two exploited zero-days, on the same profile and the same patch. KEV <b>8 Sept</b>, due <b>22 Sept</b>.</td></tr><tr><td><b>CVE-2026-75650</b></td><td>Not stated in sources read</td><td>Adobe Commerce and Magento</td><td>Added to KEV on <b>8 Sept</b> in the same batch as the two Windows zero-days. No vendor-confirmed score was obtained this run.</td></tr><tr><td><b>CVE-2026-86218</b></td><td>Not stated in sources read</td><td>N-able N-central</td><td>Static code injection. KEV <b>8 Sept</b>. Remote-monitoring and management software is high-value to intruders precisely because it is trusted across every endpoint it manages.</td></tr><tr><td><b>CVE-2026-85102 / 85103</b></td><td>Not stated in sources read</td><td>Check Point VPN</td><td>Two critical flaws, either usable for remote code execution. The Dutch <b>NCSC</b> warned on <b>11 September</b> of <b>imminent</b> exploitation. Not in any KEV batch read this run, and no CVSS was stated by the sources read.</td></tr><tr><td><b>CVE-2026-72898</b></td>")

# ---- 8. KEV section ----
rep("<li><b class=\"critc\">Due today, 12 September</b> — <b>CVE-2026-20079</b> (Cisco Secure FMC), <b>CVE-2026-19490</b> (Citrix NetScaler) and <b>CVE-2025-25249</b> (Fortinet), all added <b>9 September</b>. <span class=\"critc\" data-due=\"2026-09-12\">0 days left</span>.</li>",
    "<li><b class=\"critc\">Due today, 12 September</b> — <b>CVE-2026-20079</b> (Cisco Secure FMC), <b>CVE-2026-19490</b> (Citrix NetScaler) and <b>CVE-2025-25249</b> (Fortinet), all added <b>9 September</b>. <span class=\"critc\" data-due=\"2026-09-12\">0 days left</span>.</li><li><b>Due 22 September</b> &mdash; the <b>8 September</b> batch, newly surfaced this run and not carried by any previous edition: <b>CVE-2026-85880</b> and <b>CVE-2026-81963</b> (the two exploited Windows zero-days), <b>CVE-2026-75650</b> (Adobe Commerce and Magento) and <b>CVE-2026-86218</b> (N-able N-central). <span class=\"warnc\" data-due=\"2026-09-22\">10 days left</span>.</li>")

rep("<li><b>The 9 September bulletin is now the cleanest proof yet that BOD 26-04 sets the clock per vulnerability.</b> One alert, one add date, four CVEs — and two different deadlines <b>eleven days apart</b>: the Cisco, Citrix and Fortinet flaws were given <b>three days</b>, the Chromium flaw <b>fourteen</b>. The 4 September Chromium addition also got fourteen. So the interval tracks the individual vulnerability, not the batch: this is <b>not</b> the old BOD 22-01 uniform three-week window.</li>",
    "<li><b>The per-vulnerability clock under BOD 26-04 now has a fourth data point, and the pattern holds.</b> The 9 September bulletin remains the cleanest single proof &mdash; one alert, one add date, four CVEs, <b>two deadlines eleven days apart</b>, with Cisco, Citrix and Fortinet given <b>three days</b> and the Chromium flaw <b>fourteen</b>. The <b>4 September</b> Chromium addition also got fourteen, and the <b>8 September</b> batch surfaced this run got <b>fourteen</b> as well (added 8th, due 22nd). So across three separate add dates the interval has been either <b>three days</b> or <b>fourteen</b>, tracking the individual vulnerability rather than the batch it arrived in. This is emphatically <b>not</b> the old BOD 22-01 uniform three-week window. <b>Worth noting about the exception:</b> the only three-day deadlines seen so far attach to unauthenticated flaws in perimeter security appliances; the fourteen-day ones attach to browser and local-privilege bugs. That is a description of four observations, not a rule CISA has published.</li>")

# ---- 9. Sources ----
rep("<li><a href=\"https://www.bleepingcomputer.com/news/microsoft/microsoft-september-2026-patch-tuesday-fixes-966-flaws-2-zero-days/\" target=\"_blank\" rel=\"noopener\">BleepingComputer — Microsoft September 2026 Patch Tuesday fixes 966 flaws, 2 zero-days</a></li>",
    "<li><a href=\"https://www.bleepingcomputer.com/news/microsoft/microsoft-september-2026-patch-tuesday-fixes-966-flaws-2-zero-days/\" target=\"_blank\" rel=\"noopener\">BleepingComputer &mdash; Microsoft September 2026 Patch Tuesday fixes 966 flaws, 2 zero-days</a></li><li><a href=\"https://www.tenable.com/blog/microsofts-september-2026-patch-tuesday-addresses-964-cves-cve-2026-81963-cve-2026-85880\" target=\"_blank\" rel=\"noopener\">Tenable &mdash; September 2026 Patch Tuesday (964 CVEs; CVE-2026-81963 and CVE-2026-85880)</a></li><li><a href=\"https://www.securityweek.com/microsoft-patches-record-974-vulnerabilities-including-two-exploited-zero-days/\" target=\"_blank\" rel=\"noopener\">SecurityWeek &mdash; Microsoft patches record 974 vulnerabilities, including two exploited zero-days</a></li><li><a href=\"https://socprime.com/blog/cve-2026-85880-and-cve-2026-81963-analysis/\" target=\"_blank\" rel=\"noopener\">SOC Prime &mdash; CVE-2026-85880 and CVE-2026-81963 Windows zero-days (KEV due 22 September)</a></li><li><a href=\"https://securityaffairs.com/198705/security/microsofts-biggest-patch-tuesday-974-cves-2-zero-days-and-20-wormable-bugs.html\" target=\"_blank\" rel=\"noopener\">Security Affairs &mdash; Microsoft&rsquo;s biggest Patch Tuesday: 974 CVEs, 2 zero-days, 20 wormable bugs</a></li><li><a href=\"https://www.cisa.gov/news-events/alerts/2026/09/08/cisa-adds-four-known-exploited-vulnerabilities-catalog\" target=\"_blank\" rel=\"noopener\">CISA &mdash; Adds four known exploited vulnerabilities to catalog (8 September)</a></li><li><a href=\"https://www.hipaajournal.com/summit-pathology-data-breach/\" target=\"_blank\" rel=\"noopener\">HIPAA Journal &mdash; Summit Pathology (the 2024 incident refused above)</a></li><li><a href=\"https://databreaches.net/2024/10/30/summit-pathology-laboratories-notified-1-8-million-patients-of-a-breach-less-than-48-hours-later-they-were-sued/\" target=\"_blank\" rel=\"noopener\">DataBreaches.net &mdash; Summit Pathology notified 1.8 million patients (October 2024, dating the refusal)</a></li>")

io.open(F, "w", encoding="utf-8").write(s)
print("CY edits applied:", n)
