import io, sys
D = "/sessions/lucid-funny-planck/mnt/outputs/"
F = D + "mma-briefing.html"
s = io.open(F, encoding="utf-8").read()
n = 0
def rep(old, new):
    global s, n
    assert s.count(old) == 1, "MISS(%d): %s" % (s.count(old), old[:90])
    s = s.replace(old, new); n += 1

# ---- 1. TLDR ----
rep("<div class=\"tldr\"><b>Tale of the Tape</b> <span>Noche UFC lands in Glendale today with Jean Silva a heavy favourite over late replacement Jose Miguel Delgado — prelims at 2 PM ET, main card at 5 PM ET on Paramount+ — and this edition was built before the opening bell, so no results are published; the UFC then moves to Salt Lake City on 3 October, where Nat&aacute;lia Silva and Wang Cong contest the vacant women&rsquo;s flyweight title on the promotion&rsquo;s first numbered main card to air on CBS.</span></div>".replace("Nat&aacute;lia","Natália"),
    "<div class=\"tldr\"><b>Tale of the Tape</b> <span>Noche UFC&rsquo;s prelims are underway in Glendale and no bout had been decided when this edition was built &mdash; checked at two independent live pages, not inferred from the clock &mdash; so no result is published; the card runs thirteen bouts to a Jean Silva&ndash;Jose Miguel Delgado featherweight main event at 5 PM ET, and next Saturday the UFC is in Los Angeles for UFC 331, where flyweight champion Joshua Van and Alexandre Pantoja meet again in a rematch the books price as close to a coin flip.</span></div>")

# ---- 2. Countdown bar wording ----
rep("<span class=\"ev\"><b>Noche UFC: Silva vs Delgado</b> · Desert Diamond Arena, Glendale · prelims 2 PM ET, main card 5 PM ET — countdown runs to the main card</span>",
    "<span class=\"ev\"><b>Noche UFC: Silva vs Delgado</b> &middot; Desert Diamond Arena, Glendale &middot; prelims <b>underway</b> since 2 PM ET, main card 5 PM ET &mdash; countdown runs to the main card</span>")

# ---- 3. Top story: resolve the 13-vs-16 bout dispute ----
rep("The co-main pairs two-time flyweight champion <b>Brandon Moreno</b>, on a <b>two-fight skid</b>, with <b>Joseph Morales</b>. Card size is reported two ways: the official event page lists <b>thirteen</b> bouts while a separate listing read this run says <b>sixteen are scheduled</b>. Neither figure is resolved here.",
    "The co-main pairs two-time flyweight champion <b>Brandon Moreno</b>, on a <b>two-fight skid</b>, with <b>Joseph Morales</b>. <b>The card-size dispute is resolved this run.</b> Earlier editions printed two figures &mdash; <b>thirteen</b> bouts on the official event page against a separate listing&rsquo;s <b>sixteen</b>. Sherdog&rsquo;s live play-by-play page, fetched this run, enumerates the card bout by bout with each fighter&rsquo;s weigh-in figure, and it contains exactly <b>thirteen</b> bouts: seven prelims and six on the main card. <b>Thirteen is published; sixteen is retired.</b> The same page has all five rounds laid out for the main event, and Sherdog separately reports that <b>all fighters made weight</b>.")

# ---- 4. Upcoming cards: insert UFC 331 + 289 + 290 ----
rep("</div><div class=\"card\"><span class=\"chip new\">New</span><div class=\"dateline\">Sat 3 Oct · Delta Center, Salt Lake City UT</div>",
    "</div><div class=\"card\"><span class=\"chip new\">New</span><div class=\"dateline\">Sat 19 Sept &middot; Crypto.com Arena, Los Angeles CA</div><h3>UFC 331: Van vs Pantoja 2</h3><p>Flyweight champion <b>Joshua Van</b> defends against former titleholder <b>Alexandre Pantoja</b> in a rematch of their UFC 323 meeting. Co-main: <b>Arman Tsarukyan</b> vs <b>Mauricio Ruffy</b>.<br><b>Odds:</b> near pick-&rsquo;em, and the two books read this run disagree on who is favoured &mdash; <b>DraftKings</b> has Van <b>+100</b> / Pantoja <b>&minus;120</b>, while <b>BetOnline</b> has Van <b>&minus;105</b> / Pantoja <b>&minus;115</b>. Elsewhere on the card, <b>Tsarukyan &minus;380</b> over Ruffy and Olympic gold medallist <b>Gable Steveson &minus;1500</b> over <b>Sean Sharaf +600</b> &mdash; the heaviest line on the card.</p></div><div class=\"card\"><span class=\"chip new\">New</span><div class=\"dateline\">Sat 26 Sept &middot; UFC Fight Night 289</div><h3>Barcelos vs Rosas Jr.</h3><p>Newly sourced this run from Sherdog&rsquo;s event calendar. Venue and full card were not stated in the sources read this run, so neither is published.</p></div><div class=\"card\"><span class=\"chip new\">New</span><div class=\"dateline\">Sat 3 Oct · Delta Center, Salt Lake City UT</div>")

rep("<div class=\"card\"><div class=\"dateline\">Sat 17 Oct · UFC Fight Night</div><h3>Buckley vs Malott</h3><p><b>Joaquin Buckley</b> meets <b>Mike Malott</b> in a Fight Night main event. Venue not stated in the sources read this run.</p></div>",
    "<div class=\"card\"><span class=\"chip new\">New</span><div class=\"dateline\">Sat 10 Oct &middot; UFC Fight Night 290</div><h3>Allen vs Duncan</h3><p>Newly sourced this run from Sherdog&rsquo;s event calendar, which lists it as the next card after UFC 332. Venue not stated in the sources read this run.</p></div><div class=\"card\"><span class=\"chip\">Carried</span><div class=\"dateline\">Sat 17 Oct · UFC Fight Night</div><h3>Buckley vs Malott</h3><p><b>Joaquin Buckley</b> meets <b>Mike Malott</b> in a Fight Night main event. Venue not stated in the sources read this run. Carried from a previous edition and <b>not re-sourced this run</b>: Sherdog&rsquo;s calendar shows only the next five events and stops at 10 October, so it neither confirms nor contradicts this date.</p></div>")

# ---- 5. Build note: two-source verification, prelims underway ----
rep("<div class=\"callout\"><b>Build note — no results are published</b><p style=\"margin:0;font-size:15px;color:#c6ced6\">This edition was built at roughly <b>1:50 PM ET</b>, ahead of Noche UFC&rsquo;s <b>2 PM ET</b> prelim start. The absence of results was <b>verified at the source rather than inferred from the clock</b>: UFC.com&rsquo;s own live article, &ldquo;Prelim Results | Noche UFC&rdquo;, was fetched this run and carries all seven prelim bouts as <b>matchup previews only</b> — no winner, method or round anywhere on the page — with its publication metadata set to <b>2:00 PM ET today</b>. No result, method, round or bonus from this card appears anywhere in this edition. The next refresh after the card concludes will carry them.</p></div>",
    "<div class=\"callout\"><b>Build note &mdash; prelims underway, no result decided at build time</b><p style=\"margin:0 0 9px;font-size:15px;color:#c6ced6\">This edition was built shortly after <b>2 PM ET</b>, with Noche UFC&rsquo;s prelims <b>in progress</b>. The absence of results is again <b>verified at the source rather than inferred from the clock</b> &mdash; and this run it was verified at <b>two independent live pages</b>, both fetched at <b>2:08 PM ET</b>:</p><ul class=\"tight\" style=\"margin:0 0 9px\"><li><b>UFC.com</b>, &ldquo;Prelim Results | Noche UFC&rdquo; &mdash; carries all seven prelim bouts as <b>matchup previews only</b>, no winner, method or round anywhere on the page, with publication metadata set to <b>2:00 PM ET today</b>.</li><li><b>Sherdog</b>, &ldquo;UFC Noche 4 play-by-play, results &amp; round scoring&rdquo; &mdash; enumerates all thirteen bouts with a scoring block per round and an <b>&ldquo;Official Result&rdquo;</b> heading for each, and <b>every one of those fields is blank</b>, including the opening Aldrich&ndash;Tarin bout.</li></ul><p style=\"margin:0;font-size:15px;color:#c6ced6\">No result, method, round or bonus from this card appears anywhere in this edition. The next refresh after the card concludes will carry them. <b>One caution on Sherdog&rsquo;s page:</b> it already links a &ldquo;full Noche UFC 4 post-fight press conference&rdquo; item, which is a pre-staged placeholder rather than evidence the card has finished &mdash; it is named here so that a later run does not mistake it for a result.</p></div>")

# ---- 6. Full 13-bout table ----
rep("<tr><td><b>Jean Silva</b> (17-3) vs <b>Jose Miguel Delgado</b> (12-2)</td><td>Featherweight — main event</td><td class=\"warnc\">Not yet contested</td></tr><tr><td><b>Brandon Moreno</b> vs <b>Joseph Morales</b></td><td>Co-main event</td><td class=\"warnc\">Not yet contested</td></tr>",
    "<tr><td><b>Jean Silva</b> (17-3) vs <b>Jose Miguel Delgado</b> (12-2)</td><td>Featherweight &mdash; main event, five rounds (145 / 145.5)</td><td class=\"warnc\">Not yet contested</td></tr><tr><td><b>Brandon Moreno</b> vs <b>Joseph Morales</b></td><td>Co-main event (125.5 / 125.5)</td><td class=\"warnc\">Not yet contested</td></tr><tr><td><b>Tommy McMillen</b> vs <b>Marwan Rahiki</b></td><td>Main card &mdash; 145 / 145.5</td><td class=\"warnc\">Not yet contested</td></tr><tr><td><b>Manon Fiorot</b> vs <b>Alexa Grasso</b></td><td>Main card &mdash; 125 / 125</td><td class=\"warnc\">Not yet contested</td></tr><tr><td><b>Curtis Blaydes</b> vs <b>Waldo Cortes-Acosta</b></td><td>Main card &mdash; 260 / 262</td><td class=\"warnc\">Not yet contested</td></tr><tr><td><b>Dan Ige</b> vs <b>David Martinez</b></td><td>Main card &mdash; 135.5 / 135</td><td class=\"warnc\">Not yet contested</td></tr>")

rep("<div class=\"note\">Full prelim card and records as published by UFC.com this run. Performance bonuses will be added once the promotion announces them.</div>",
    "<div class=\"note\">All <b>thirteen</b> bouts, newly complete this run. Prelim records are as published by UFC.com; the six main-card bouts and every weigh-in figure in brackets come from Sherdog&rsquo;s play-by-play page, fetched this run &mdash; earlier editions carried the seven prelims only. Sherdog reports all fighters made weight. Performance bonuses will be added once the promotion announces them.</div>")

# ---- 7. Around the Sport ----
rep("<li><b>Noche UFC shares its night with boxing:</b> the promotion is cross-promoting <b>Garcia vs Benn</b> on Paramount+ alongside tonight&rsquo;s card.</li>",
    "<li><b>Noche UFC shares its night with boxing:</b> the promotion is cross-promoting <b>Garcia vs Benn</b> on Paramount+ alongside tonight&rsquo;s card. Corroborated this run: Sherdog reports <b>Ryan Garcia and Conor Benn made weight</b> for the Zuffa Boxing event.</li><li><b>Dana White says Ilia Topuria is ready to fight again</b> following the <b>first UFC loss</b> of his career &mdash; the description of it as his first is Sherdog&rsquo;s, and it is consistent with the lightweight title change recorded on the board below.</li><li><b>Islam Makhachev has responded publicly to Shavkat Rakhmonov</b> over what Sherdog&rsquo;s headline calls a UFC title snub. The welterweight champion&rsquo;s next booking is not stated in the sources read this run.</li><li><b>Jean Silva has predicted an early finish</b> in tonight&rsquo;s main event, per Sherdog. It is a prediction, not a result, and nothing on this page treats it as one.</li><li><b>Brandon Moreno&rsquo;s own framing of the skid</b> is newly sourced: Sherdog reports a candid &ldquo;worst enemy&rdquo; admission from the former champion after two UFC losses, which corroborates the two-fight skid noted above.</li>")

# ---- 8. Rankings & Business ----
rep("<li><b>No viewership, gate or revenue figures</b> were stated in any source read this run, so none are published. TKO Group financials are likewise omitted rather than estimated.</li>",
    "<li><b>Next week&rsquo;s title fight is priced as a coin flip, and the books disagree on which way.</b> For <b>UFC 331</b> on 19 September, DraftKings opened flyweight champion <b>Joshua Van at +100</b> with <b>Pantoja &minus;120</b>, while BetOnline has it the other way round at <b>Van &minus;105 / Pantoja &minus;115</b>. Both are printed; neither is averaged. The widest line anywhere on that card is <b>Gable Steveson at &minus;1500</b>.</li><li><b>No viewership, gate or revenue figures</b> were stated in any source read this run, so none are published. TKO Group financials are likewise omitted rather than estimated.</li>")

# ---- 9. Champions verification note ----
rep("<div class=\"note\">Verification note — fifth consecutive regression on the same belt. ESPN&rsquo;s &ldquo;Current and all-time UFC champions&rdquo; page was read this run and returned <b>all eight men&rsquo;s divisions correctly</b>, including Carlos Ulberg at light heavyweight, the entry that had regressed to Alex Pereira two runs ago. It again seated <b>Valentina Shevchenko</b> at women&rsquo;s flyweight on a &ldquo;won title Sept. 14, 2024&rdquo; entry that predates her vacating the belt. That claim is refused and VACANT is published. The board above is derived per division from the most recent title-changing card, not copied from any single list.</div>",
    "<div class=\"note\">Verification note &mdash; <b>the cross-check was not available this run.</b> ESPN&rsquo;s &ldquo;Current and all-time UFC champions&rdquo; page was requested and returned <b>no content at all</b>. That is reported here rather than presented as a clean check: a source that returns nothing is not a source that agrees with the board. The board above is published from the standing block, derived per division from the most recent title-changing card, and is <b>not</b> copied from any single list. <b>Two of its rows did pick up independent corroboration this run, from coverage that was not about the champions board at all:</b> UFC 331 betting coverage repeatedly describes <b>Joshua Van</b> as the current flyweight champion and Pantoja as the former titleholder, and Sherdog describes <b>Ilia Topuria</b> as having taken the first UFC loss of his career &mdash; consistent with the lightweight belt having changed hands at Freedom 250. The standing regression guards are retained in full: five of the six preceding runs saw a champions source regress, four of them at women&rsquo;s flyweight, where a <b>&ldquo;won title Sept. 14, 2024&rdquo;</b> entry for <b>Valentina Shevchenko</b> predates her vacating the belt and is refused every time it appears.</div>")

# ---- 10. Sources ----
rep("<li><a href=\"https://www.sherdog.com/news/news/UFC-Noche-4-Silva-vs-Delgado-playbyplay-results-round-scoring-202770\" target=\"_blank\" rel=\"noopener\">Sherdog — UFC Noche 4 play-by-play and round scoring</a></li>",
    "<li><a href=\"https://www.sherdog.com/news/news/UFC-Noche-4-Silva-vs-Delgado-playbyplay-results-round-scoring-202770\" target=\"_blank\" rel=\"noopener\">Sherdog &mdash; UFC Noche 4 play-by-play and round scoring (fetched this run; all result fields blank)</a></li><li><a href=\"https://www.sherdog.com/news/news/Noche-UFC-4-weighin-results-All-fighters-make-weight-202769\" target=\"_blank\" rel=\"noopener\">Sherdog &mdash; Noche UFC 4 weigh-in results: all fighters make weight</a></li><li><a href=\"https://sports.yahoo.com/articles/ufc-331-joshua-van-vs-020025667.html\" target=\"_blank\" rel=\"noopener\">Yahoo Sports &mdash; UFC 331: Joshua Van vs. Alexandre Pantoja 2, odds and what to know</a></li><li><a href=\"https://www.mmamania.com/ufc-odds/462743/ufc-331-opening-odds-tight-race-van-pantoja-2-arman-gable-steveson-huge-betting-favorites\" target=\"_blank\" rel=\"noopener\">MMA Mania &mdash; UFC 331 opening odds</a></li><li><a href=\"https://www.sherdog.com/events/UFC-331-Van-vs-Pantoja-2-113633\" target=\"_blank\" rel=\"noopener\">Sherdog &mdash; UFC 331: Van vs. Pantoja 2 event page</a></li><li><a href=\"https://www.sherdog.com/news/news/Dana-White-says-Ilia-Topuria-is-ready-to-fight-following-first-UFC-loss-202761\" target=\"_blank\" rel=\"noopener\">Sherdog &mdash; Dana White says Ilia Topuria is ready to fight following first UFC loss</a></li><li><a href=\"https://www.sherdog.com/news/news/Islam-Makhachev-fires-Back-at-Shavkat-Rakhmonov-over-UFC-title-snub-202752\" target=\"_blank\" rel=\"noopener\">Sherdog &mdash; Islam Makhachev fires back at Shavkat Rakhmonov over UFC title snub</a></li><li><a href=\"https://www.sherdog.com/news/news/Brandon-Moreno-makes-candid-worst-enemy-admission-after-2-UFC-losses-202766\" target=\"_blank\" rel=\"noopener\">Sherdog &mdash; Brandon Moreno makes candid &lsquo;worst enemy&rsquo; admission after 2 UFC losses</a></li>")

io.open(F, "w", encoding="utf-8").write(s)
print("MMA edits applied:", n)
