import io
D = "/sessions/lucid-funny-planck/mnt/outputs/"
F = D + "wallstreet-briefing.html"
s = io.open(F, encoding="utf-8").read()
n = 0
def rep(old, new):
    global s, n
    assert s.count(old) == 1, "MISS(%d): %s" % (s.count(old), old[:90])
    s = s.replace(old, new); n += 1

# ---- 1. TLDR ----
rep("<div class=\"tldr\"><b>The Tape</b> <span>Markets are closed for the weekend after Wall Street snapped a four-day losing streak on Friday, all three indexes rising about 1% as both crude benchmarks settled sharply lower — WTI at $100.05 and Brent at $104.61 — on news that Iran will meet Gulf states in Oman about the Strait of Hormuz; every index still finished the week lower, and the equal-weight S&amp;P 500&rsquo;s 1.87% weekly fall shows how much of that damage the mega-caps concealed.</span></div>",
    "<div class=\"tldr\"><b>The Tape</b> <span>Markets are closed for the weekend after Friday&rsquo;s roughly 1% rally snapped a four-day losing streak, with all three indexes still finishing the week lower and the equal-weight S&amp;P 500&rsquo;s 1.87% weekly fall showing how much of that damage the mega-caps concealed; crude settled sharply lower on Friday &mdash; WTI $100.05, Brent $104.61 &mdash; yet closed the week above $100 for the first time since May, and the week ahead brings three central bank decisions, the Federal Reserve&rsquo;s on Wednesday with projections attached.</span></div>")

# ---- 2. Lead: sector detail now sourced; hike-odds dispute ----
rep("Friday itself was concentrated in AI infrastructure. Oracle&rsquo;s capital-spending guidance",
    "<b>Newly sourced this run, and it retires a carried line:</b> Friday&rsquo;s advance was led by <b>Communication Services, Consumer Discretionary and Information Technology</b>, with <b>Communication Services up 1.6%</b> to pace the S&amp;P 500 sector table and <b>T-Mobile up more than 3.5%</b> at the front of it. Previous editions carried a &ldquo;nine of eleven sectors higher, health care and utilities lagging&rdquo; line that was never re-sourced; it is <b>dropped</b> in favour of the sector detail above, which was.</p><p style=\"margin:0 0 10px;font-size:15px;color:#c6ced6\">Friday itself was concentrated in AI infrastructure. Oracle&rsquo;s capital-spending guidance")

rep("Attention now turns to the <b>FOMC meeting on 15&ndash;16 September</b>, with the decision <b>Wednesday 16 September at 2 PM ET</b> and a <b>Summary of Economic Projections</b> alongside it. Futures price roughly a <b>90% probability of a quarter-point increase</b> — an increase, which is what makes the projections the more consequential half of the release.",
    "Attention now turns to the <b>FOMC meeting on 15&ndash;16 September</b>, with the decision <b>Wednesday 16 September at 2 PM ET</b> and a <b>Summary of Economic Projections</b> alongside it. The Wednesday timing is <b>independently re-confirmed this run</b> by a second week-ahead source, which strengthens the previous edition&rsquo;s refusal of a preview that had put the Fed on Thursday. The market is pricing an <b>increase</b> rather than a cut &mdash; which is what makes the projections the more consequential half of the release &mdash; but <b>how large a probability is genuinely in dispute</b>, and both readings are printed below rather than reconciled here.")

# ---- 3. Movers: add small-cap card + T-Mobile, and grade HPE ----
rep("<div class=\"card\"><span class=\"chip new\">New</span><span class=\"chip warn\">Breadth</span><h3>The average stock had a much worse week</h3>",
    "<div class=\"card\"><span class=\"chip new\">New</span><span class=\"chip ok\">Sector leader</span><h3>T-Mobile <span class=\"up\">+3.5%</span></h3><p>Newly sourced this run. T-Mobile rose <b>more than 3.5%</b> to lead <b>Communication Services</b>, which was in turn the best S&amp;P 500 sector on the day at <b>+1.6%</b>. It is the one Friday mover on this page that has nothing to do with the AI-hardware trade.</p></div><div class=\"card\"><span class=\"chip new\">New</span><span class=\"chip warn\">Small caps</span><h3>Outside the S&amp;P, much larger moves &mdash; and one that is not published</h3><p>A market-review source read this run lists <b>Tenon Medical +53.8%</b> on heavy volume and <b>ACV Auctions +44.8%</b> among Friday&rsquo;s small-cap movers. The same list carries <b>Gauzy Ltd. at &minus;94.8%</b>, and that figure is <b>deliberately not published as a price move</b>: a single-session fall of that size almost always reflects a corporate action such as a reverse split or a re-listing rather than trading, and no source read this run states what happened. It is named here so it is not silently dropped.</p></div><div class=\"card\"><span class=\"chip new\">New</span><span class=\"chip warn\">Breadth</span><h3>The average stock had a much worse week</h3>")

rep("HPE led the S&amp;P 500. The <b>12.2%</b> figure is re-confirmed this run; other reads put the move at <b>12.44%</b> (to a close of <b>$62.09</b>) or &ldquo;about 11%&rdquo;, and all three are printed rather than averaged.",
    "HPE led the S&amp;P 500 &mdash; a description re-confirmed by a fresh source this run. The <b>12.2%</b> figure is carried; other reads put the move at <b>12.44%</b> (to a close of <b>$62.09</b>), &ldquo;about 11%&rdquo;, and, newly this run, &ldquo;<b>up nearly 11%</b>&rdquo;. All four are printed rather than averaged; what every source agrees on is that HPE was the index&rsquo;s single biggest gainer.")

# ---- 4. Sector heat note: retire the carried line ----
rep("<div class=\"note\">Verified this run: on the week the equal-weight S&amp;P fell 1.87% against 0.68% for the cap-weighted index, and small caps fell 2.38%. The sector detail — nine of eleven S&amp;P sectors higher on Friday, health care and utilities lagging — is <b>carried from the previous edition</b> and was not re-sourced this run. The map below is live and will show the next session from Monday.</div>",
    "<div class=\"note\">Verified this run: Friday&rsquo;s leading sectors were <b>Communication Services, Consumer Discretionary and Information Technology</b>, with Communication Services the best at <b>+1.6%</b>. The previously carried &ldquo;nine of eleven sectors higher, health care and utilities lagging&rdquo; line has been <b>retired</b> &mdash; it was never re-sourced, and this run produced sourced sector detail to replace it. On the week the equal-weight S&amp;P fell <b>1.87%</b> against <b>0.68%</b> for the cap-weighted index, and small caps fell <b>2.38%</b>. The map below is live and will show the next session from Monday.</div>")

# ---- 5. Rates table: 2-year dispute, 30-year, Fed odds ----
rep("<tr><td>2-year Treasury</td><td class=\"warnc\">4.65% / 4.396% — disputed</td><td>Two reads this run disagree materially. One puts the two-year at about <b>4.65%</b>, a <b>two-year high</b>, after the CPI print raised the odds of a hike; a carried read gives <b>4.396%</b> and says the two-year exceeded 4.5% earlier in the week for the first time since 2024. These cannot both describe Friday&rsquo;s close. Neither is dropped and neither is averaged until a primary source settles it.</td></tr>",
    "<tr><td>2-year Treasury</td><td>4.63%</td><td><b>The standing dispute narrows this run.</b> The dated Friday yields snapshot read this run gives the two-year <b>finishing 11 September at 4.63%</b> &mdash; from the same source, and the same sentence, as the 4.96% ten-year above. That figure is published. The previously disputed pair is named rather than deleted: <b>4.65%</b> (described as a two-year high after the CPI print) is close enough to be the same close rounded differently, while the carried <b>4.396%</b> cannot describe the same session and is <b>retired</b>.</td></tr>")

rep("<tr><td>30-year Treasury</td><td>Not stated in sources read</td><td>Reported at levels last seen in 2007; no closing figure in sources read this run.</td></tr>",
    "<tr><td>30-year Treasury</td><td>No Friday settlement in sources read</td><td>Reported at levels last seen in 2007. An <b>undated live quote</b> read this run pairs a 30-year of <b>5.36%</b> with a ten-year of <b>4.98%</b> &mdash; but that ten-year does not match Friday&rsquo;s dated 4.96% close, which tells you the pair is a current streaming quote and not an 11 September settlement. On that reasoning the 5.36% is <b>not</b> published as a Friday figure.</td></tr>")

rep("Futures price roughly a <b>90% probability of a 25bp increase</b> (CME FedWatch as of 11 September).</td></tr>",
    "<b>Hike odds are in dispute and both readings are printed:</b> a post-CPI read this run puts the probability of a <b>25bp increase at about 71%, up from 61%</b> before the inflation data, while the carried reading is roughly <b>90%</b> (CME FedWatch as of 11 September). They are not averaged. What both agree on is the direction &mdash; the debate is about a hike, not a cut.</td></tr>")

# ---- 6. Oil rows: week above $100 first time since May ----
rep("WTI gained <b>9.4% on the week</b>, the larger of the two benchmarks&rsquo; weekly moves, and finished a fraction above the $100 line it had crossed on the way up.",
    "WTI gained <b>9.4% on the week</b>, the larger of the two benchmarks&rsquo; weekly moves, and finished a fraction above the $100 line it had crossed on the way up. Newly sourced this run: that is oil&rsquo;s <b>first weekly close above $100 since May</b>, and the <b>biggest weekly gain since July</b>.")

# ---- 7. On the Radar ----
rep("<li><b>Inflation is still the binding constraint.</b> Headline CPI ran <b>3.4% year on year</b> against the Fed&rsquo;s <b>2%</b> target; core came in a tenth above forecast at <b>+0.3% m/m</b>, which is why hike odds jumped rather than the headline.</li>",
    "<li><b>Inflation is still the binding constraint, but the core reading cuts both ways.</b> Headline CPI ran <b>3.4% year on year</b> against the Fed&rsquo;s <b>2%</b> target, and core came in a tenth above forecast at <b>+0.3% m/m</b>, up from <b>+0.2%</b> in July &mdash; which is why hike odds jumped rather than the headline. Newly sourced this run, and pointing the other way: the <b>annual</b> core rate <b>slowed to 2.4%</b>, its lowest since 2021. A firming monthly print inside a cooling annual trend is exactly the ambiguity the Summary of Economic Projections will have to resolve.</li><li><b>Wednesday is a stacked day beyond the Fed.</b> The same week-ahead source puts <b>UK CPI</b>, <b>US retail sales</b> and <b>New Zealand GDP</b> on the Wednesday alongside the FOMC decision.</li><li><b>The Treasury is buying bonds back into the yield spike.</b> Coverage this run notes the ten-year touching its highest since 2023 <b>despite</b> a <b>$6 billion buyback plan</b> from Treasury Secretary Bessent &mdash; the failure of the buyback to hold yields down is the point, not the buyback itself.</li><li><b>Diesel is the quiet part of the oil story.</b> One report on the week&rsquo;s crude gains carries <b>US diesel at a record high</b>. Crude headlines are about the Strait of Hormuz; the refined-product price is what reaches the freight and food bills.</li>")

rep("<li><b>Oil is still the swing factor.</b> Friday&rsquo;s near-3% Brent pullback was the proximate cause of the equity rebound, so any renewed spike reverses the trade and re-prices the front end.</li>",
    "<li><b>Oil is still the swing factor.</b> Friday&rsquo;s near-3% Brent pullback was the proximate cause of the equity rebound, so any renewed spike reverses the trade and re-prices the front end &mdash; and despite that pullback the week was crude&rsquo;s <b>biggest since July</b>, ending above $100 for the first time since May.</li>")

# ---- 8. Sources ----
rep("<li><a href=\"https://tradingeconomics.com/commodity/brent-crude-oil\" target=\"_blank\" rel=\"noopener\">Trading Economics — Brent crude oil</a></li>",
    "<li><a href=\"https://tradingeconomics.com/commodity/brent-crude-oil\" target=\"_blank\" rel=\"noopener\">Trading Economics &mdash; Brent crude oil</a></li><li><a href=\"https://finance.yahoo.com/markets/stocks/articles/stock-market-today-futures-rise-103943781.html\" target=\"_blank\" rel=\"noopener\">Yahoo Finance &mdash; Markets News, Sept. 11, 2026: stocks finish week lower; indexes jump Friday as oil pulls back</a></li><li><a href=\"https://investrade.com/market-review-september-11-2026/\" target=\"_blank\" rel=\"noopener\">Investrade &mdash; Market review: September 11, 2026 (sector leadership, small-cap movers)</a></li><li><a href=\"https://finance.yahoo.com/energy/articles/oil-prices-poised-end-week-105344992.html\" target=\"_blank\" rel=\"noopener\">Yahoo Finance &mdash; Oil prices poised to end week above $100 for first time since May</a></li><li><a href=\"https://www.rigzone.com/news/wire/oil_posts_biggest_weekly_gain_since_july-11-sep-2026-184602-article/\" target=\"_blank\" rel=\"noopener\">Rigzone &mdash; Oil posts biggest weekly gain since July</a></li><li><a href=\"https://www.aol.com/articles/oil-prices-set-end-week-011257000.html\" target=\"_blank\" rel=\"noopener\">AOL &mdash; Oil set for weekly gain of over 7% on supply disruptions; US diesel hits record high</a></li><li><a href=\"https://www.cnbc.com/2026/09/09/treasury-yields-oil-inflation.html\" target=\"_blank\" rel=\"noopener\">CNBC &mdash; 10-year Treasury yield touches highest since 2023 despite Bessent&rsquo;s $6 billion bond buyback plan</a></li><li><a href=\"https://www.mql5.com/en/blogs/post/775729\" target=\"_blank\" rel=\"noopener\">Traders&rsquo; Blogs &mdash; High-impact economic events, September 14&ndash;20, 2026</a></li><li><a href=\"https://www.litefinance.org/blog/analysts-opinions/weekly-economic-calendar-for-14092026-20092026/\" target=\"_blank\" rel=\"noopener\">LiteFinance &mdash; Weekly economic calendar, 14&ndash;20 September 2026 (BoJ timing)</a></li><li><a href=\"https://www.stl.news/sp-500-winners-and-losers-this-week-sept-11-2026/\" target=\"_blank\" rel=\"noopener\">STL.News &mdash; S&amp;P 500 winners and losers this week, Sept. 11, 2026</a></li>")

io.open(F, "w", encoding="utf-8").write(s)
print("WS edits applied:", n)
