import re
def rep(s,a,b,n=1):
    assert s.count(a)==n,(a[:80],s.count(a)); return s.replace(a,b)
# ---------- WALL STREET
f='wallstreet-briefing.html'; s=open(f).read()
old_tldr=re.search(r'<div class="tldr"><b>The Tape</b><span>(.*?)</span></div>',s).group(1)
new_tldr="As of 1:00 PM ET Friday stocks held solid gains &mdash; the Dow up 0.72%, the Nasdaq 0.46% and the S&amp;P 500 0.39% &mdash; slightly below their midday highs, as oil fell on Iran&rsquo;s offer to reopen the Strait of Hormuz and Treasury yields eased from multi-decade highs."
s=rep(s,old_tldr,new_tldr)
h=re.search(r'<div class="lead"><h3>(.*?)</h3>',s).group(1)
s=rep(s,h,"As of 1:00 PM ET: Dow up 0.72%, Nasdaq up 0.46%, S&amp;P 500 up 0.39% as oil slides and yields ease")
s=rep(s,"Wall Street is ending a volatile week on a firmer note, and after narrowing in late morning the gains widened again around midday. With about 3 hours 45 minutes left in the session (about 12:15 PM ET), Yahoo Finance&rsquo;s quote strip showed the Dow Jones Industrial Average up about 442 points, or 0.86%, the Nasdaq Composite up 0.63% and the S&amp;P 500 up 0.53%; the Russell 2000 was up just 0.10%, and the Cboe Volatility Index was down 3.51% at 15.12. Earlier, at 11:47 AM ET, the Dow had been up only 0.3% with the S&amp;P 500 and Nasdaq barely above flat (Yahoo Finance).",
"Wall Street is ending a volatile week on a firmer note. At 1:00 PM ET the Dow Jones Industrial Average was up about 370 points, or 0.72%, the Nasdaq Composite was up 0.46% and the S&amp;P 500 was up 0.39% &mdash; a little below the session&rsquo;s midday readings. Around 12:15 PM ET Yahoo Finance&rsquo;s quote strip had shown the Dow up 0.86%, the Nasdaq up 0.63% and the S&amp;P 500 up 0.53%, with the Cboe Volatility Index down 3.51% at 15.12. Bloomberg said Treasury yields dropped from multi-decade highs, though a gauge of volatility was still set for its biggest weekly jump in over a year.")
s=rep(s,"Intraday index moves are from Yahoo Finance&rsquo;s quote strip fetched at this 12:33 PM ET refresh, which read &ldquo;U.S. markets close in 3h 45m&rdquo; (about 12:15 PM ET); the point changes are consistent with Thursday&rsquo;s official closes.",
"The 1:00 PM ET index moves are from a time-stamped quote reading returned by this 1:03 PM ET refresh&rsquo;s market search (Dow +370.34 points, Nasdaq +123.74 points &mdash; both consistent with Thursday&rsquo;s official closes); the 12:15 PM ET comparison is Yahoo Finance&rsquo;s quote strip.")
s=rep(s,'<a href="https://www.cnbc.com/2026/09/24/stock-market-today-live-updates.html" style="color:var(--acc2)">CNBC live updates</a> &middot; ',
 '<a href="https://www.cnbc.com/2026/09/24/stock-market-today-live-updates.html" style="color:var(--acc2)">CNBC live updates</a> &middot; <a href="https://www.bloomberg.com/news/articles/2026-09-24/stock-market-today-dow-s-p-live-updates" style="color:var(--acc2)">Bloomberg live (Sept 25)</a> &middot; ')
open(f,'w').write(s)
# ---------- CYBER
f='cyber-briefing.html'; s=open(f).read()
old=re.search(r'<div class="tldr"><b>The Wire</b><span>(.*?)</span></div>',s).group(1)
s=rep(s,old,"CISA today added an actively exploited Microsoft SharePoint Server code-injection flaw to its KEV catalog with a September 28 federal deadline, as four exploited Arista, F5 and Check Point flaws hit their deadline today and crypto exchange Bitget says suspected North Korean hackers stole $351.6 million.")
s=rep(s,"reach their federal deadline today, a maximum-severity WSO2 API Manager flaw has been under attack since September 13, and suspected",
 "reach their federal deadline today, CISA added an exploited SharePoint Server flaw with a three-day deadline, a maximum-severity WSO2 API Manager flaw has been under attack since September 13, and suspected")
s=rep(s,"<h3>Four exploited appliance flaws are due today; the CVSS 10.0 WSO2 flaw is due Sunday</h3>",
 "<h3>Four exploited appliance flaws are due today; WSO2 is due Sunday and a newly listed SharePoint flaw Monday</h3>")
s=rep(s,"WSO2&rsquo;s May 3 advisory lists the fixed update levels (for example API Manager 4.2.0 update level 197 and 4.1.0 update level 257). These dates match the KEV section below.",
 "WSO2&rsquo;s May 3 advisory lists the fixed update levels (for example API Manager 4.2.0 update level 197 and 4.1.0 update level 257). <span class=\"tag good\">New</span> On September 25 CISA also added <b>CVE-2026-65660</b>, a code-injection flaw in on-premises SharePoint Server 2016, 2019 and Subscription Edition that lets an authorized attacker execute code over the network (CVSS 3.1 8.8 per NVD; Microsoft first published it in August as a 6.5 spoofing bug), with a federal deadline of <b>September 28, 2026 (3 days left)</b> and forensic triage required under BOD 26-04 (HOL, citing the KEV catalog). Fixed builds are the August 2026 updates: 16.0.5565.1001 (2016), 16.0.10417.20198 (2019) and 16.0.19725.20522 (Subscription Edition). These dates match the KEV section below.")
s=rep(s,'<a href="https://security.docs.wso2.com/en/latest/security-announcements/security-advisories/2026/WSO2-2026-5328/" style="color:var(--acc2)">WSO2 advisory WSO2-2026-5328</a></p></div>\n<h2 class="sec">Threat Actor',
 '<a href="https://security.docs.wso2.com/en/latest/security-announcements/security-advisories/2026/WSO2-2026-5328/" style="color:var(--acc2)">WSO2 advisory WSO2-2026-5328</a> &middot; <a href="https://www.cisa.gov/news-events/alerts/2026/09/25/cisa-adds-two-known-exploited-vulnerabilities-catalog" style="color:var(--acc2)">CISA (Sept 25 alert)</a> &middot; <a href="https://hol.org/blog/cve-2026-65660-microsoft-sharepoint-code-injection-kev" style="color:var(--acc2)">HOL (SharePoint KEV)</a></p></div>\n<h2 class="sec">Threat Actor')
s=rep(s,'<tr><th>CVE</th><th>CVSS</th><th>Affected</th><th>Note</th></tr>\n',
 '<tr><th>CVE</th><th>CVSS</th><th>Affected</th><th>Note</th></tr>\n<tr><td class="mono">CVE-2026-65660</td><td class="warnc">8.8</td><td>SharePoint Server 2016, 2019, Subscription Edition (on-prem; fixed in August 2026 builds)</td><td>New: code injection letting an authorized attacker run code; Microsoft first listed it as a 6.5 spoofing flaw. Canada&rsquo;s Cyber Centre reported active exploitation Sept 24. KEV added Sept 25, due Sept 28.</td></tr>\n<tr><td class="mono">CVE-2026-67279</td><td>&mdash;</td><td>MikroTik RouterOS (fixed in 7.24.2, 7.23.4, 6.49.21)</td><td>New: SSH rekey flaw lets an unauthenticated client run commands and create or overwrite files (CERT Polska). KEV added Sept 25; score and due date not confirmed this edition.</td></tr>\n')
s=rep(s,'<h2 class="sec">CISA KEV &amp; Federal Deadlines</h2><div class="panel"><ul class="bul">\n',
 '<h2 class="sec">CISA KEV &amp; Federal Deadlines</h2><div class="panel"><ul class="bul">\n<li><span class="tag good">New</span> <b>CVE-2026-65660</b> (Microsoft SharePoint Server) &mdash; added Sept 25 &mdash; due <b>Sept 28</b> <span class="warnc">(3 days left)</span></li>\n<li><span class="tag good">New</span> <b>CVE-2026-67279</b> (MikroTik RouterOS) &mdash; added Sept 25 &mdash; due date not confirmed by a source this edition</li>\n')
s=rep(s,'Countdowns are computed from today, Sept 25. Sources: ',
 'Countdowns are computed from today, Sept 25. Sources: <a href="https://www.cisa.gov/news-events/alerts/2026/09/25/cisa-adds-two-known-exploited-vulnerabilities-catalog" style="color:var(--acc2)">CISA (Sept 25)</a> &middot; <a href="https://hol.org/blog/cve-2026-65660-microsoft-sharepoint-code-injection-kev" style="color:var(--acc2)">HOL (SharePoint due date)</a> &middot; ')
s=rep(s,'<footer><div class="dv">The Cyber Wire</div><div class="srcs">Sources: ',
 '<footer><div class="dv">The Cyber Wire</div><div class="srcs">Sources: <a href="https://www.cisa.gov/news-events/alerts/2026/09/25/cisa-adds-two-known-exploited-vulnerabilities-catalog" style="color:inherit">CISA Sept 25 alert</a> &middot; <a href="https://windowsforum.com/news/cve-2026-65660-cisa-flags-exploited-sharepoint-code-injection.446015/" style="color:inherit">WindowsForum (SharePoint &amp; MikroTik KEV)</a> &middot; <a href="https://hol.org/blog/cve-2026-65660-microsoft-sharepoint-code-injection-kev" style="color:inherit">HOL (SharePoint KEV)</a> &middot; <a href="https://thehackernews.com/2026/09/sharepoint-flaw-initially-listed-as.html" style="color:inherit">The Hacker News (SharePoint)</a> &middot; <a href="https://cert.pl/en/posts/2026/09/mikrotik-routeros-cve/" style="color:inherit">CERT Polska (RouterOS)</a> &middot; ')
open(f,'w').write(s)
# ---------- INDEX
f='index.html'; s=open(f).read()
s=rep(s,old,"CISA today added an actively exploited Microsoft SharePoint Server code-injection flaw to its KEV catalog with a September 28 federal deadline, as four exploited Arista, F5 and Check Point flaws hit their deadline today and crypto exchange Bitget says suspected North Korean hackers stole $351.6 million.")
s=rep(s,old_tldr,new_tldr)
open(f,'w').write(s)
print('ok')
