# -*- coding: utf-8 -*-
import io
F='mma-briefing.html'
s=io.open(F,encoding='utf-8').read()
def rep(old,new):
    global s
    n=s.count(old); assert n==1,"count=%d %r"%(n,old[:90]); s=s.replace(old,new)

# 1 — TLDR
rep(u"<div class=\"tldr\"><b>Tale of the Tape</b> <span>It is fight week in Shanghai: bantamweight contenders Umar Nurmagomedov and Song Yadong headline Saturday's card at the Oriental Sports Center, with Nurmagomedov a −500 favourite on two of the three lines seen this run and −470 on the third — and a stale champions list surfaced again today and was rejected.</span></div>",
    u"<div class=\"tldr\"><b>Tale of the Tape</b> <span>It is fight week in Shanghai: bantamweight contenders Umar Nurmagomedov and Song Yadong headline Saturday's card at the Oriental Sports Center, with Nurmagomedov a −500 favourite on two of the three lines seen this run and −470 on the third — and ESPN's champions page returned the correct board this time, after serving a stale one an hour ago.</span></div>")

# 2 — Champions Board note: ESPN came back correct
rep(u'<div class="note" style="margin:0 0 10px"><b>Trap logged at 12:05, and the board did not move.</b> A fresh query against ESPN\'s "Current and all-time UFC champions" page returned a summary listing <b>Alex Pereira at light heavyweight, Khamzat Chimaev at middleweight and Ilia Topuria at lightweight</b>. Those three lines are the exact regression this briefing has published wrongly before: Pereira vacated at 205 and lost the interim-heavyweight bid to Ciryl Gane, Sean Strickland took the middleweight belt by split decision at UFC 328 on May 9, and Justin Gaethje stopped Topuria in the fourth round at Freedom 250 on June 14. <b>The stale summary was rejected and the verified board below is unchanged</b> — a champions list that predates the most recent title fight is wrong no matter how authoritative the domain.</div>',
    u'<div class="note" style="margin:0 0 10px"><b>Re-verified at 12:38 — and this time ESPN agreed.</b> The same query against ESPN\'s "Current and all-time UFC champions" page returned <b>Tom Aspinall (heavyweight, since June 21, 2025), Carlos Ulberg (KO1 Jiří Procházka, UFC 327, April 11, 2026), Sean Strickland (split decision over Khamzat Chimaev, UFC 328, May 9, 2026), Islam Makhachev (UD Jack Della Maddalena, UFC 322, November 15, 2025), Justin Gaethje (TKO4 Ilia Topuria, Freedom 250, June 14, 2026) and Alexander Volkanovski (UD Diego Lopes, UFC 314, April 12, 2025)</b> — six belts matching the board below on champion, method and date. <span style="color:var(--mut)"><b>An hour earlier the same page returned a stale summary</b> listing Pereira at 205, Chimaev at 185 and Topuria at 155 — the exact three-belt regression this briefing exists to prevent — and it was rejected. The board did not move then and does not move now. <b>The lesson holds either way: the board is confirmed against the latest results, not against the reputation of the site, and the same URL can return either answer.</b> The remaining five divisions were not restated in this run\'s ESPN return and are carried from the verified record.</span></div>')

# 3 — Blaydes bullet upgraded
rep(u'<li><b>Roster churn — the eight-fight deal now has a name.</b> Bloody Elbow reported on August 21 that a former UFC title challenger had survived a run of surprise roster removals by signing a new <b>eight-fight deal</b>; coverage seen this run identifies him as UFC heavyweight <b>Curtis Blaydes</b>. The "title challenger" descriptor is Bloody Elbow\'s headline wording, reported as such.</li>',
    u'<li><b>Roster churn — the eight-fight deal, now with the detail behind it.</b> Bloody Elbow reported on <b>August 21</b> that a fighter had survived a run of surprise roster removals by signing a new <b>eight-fight deal</b>. Coverage fetched this run names him as heavyweight <b>Curtis Blaydes</b>, describes him as the <b>No. 10-ranked contender</b> and a <b>one-time interim heavyweight title challenger</b>, and reports he revealed the deal in an interview with <b>James Lynch</b> for Ozoon. Blaydes has <b>lost three of his last five</b>; his most recent outing was a loss to <b>Josh Hokit</b> at <b>UFC 327</b>, and the entertaining nature of that fight is cited as having helped him secure the long-term deal. <span style="color:var(--mut)">"Interim heavyweight title challenger" is now the sourced descriptor and replaces the looser "title challenger" wording carried earlier today; he has never fought for the undisputed belt.</span></li>')

# 4 — Sacramento purse, appended to the bonuses block
rep(u'<b>$25,000 finish bonuses:</b> Jamall Emmers, Shanelle Dyer, Jackson McVey, Marcio Barbosa, Chris Padilla, Anthony Wint and Reinier de Ridder — fighters who finished their bouts without taking one of the $100,000 awards.',
    u'<b>$25,000 finish bonuses:</b> Jamall Emmers, Shanelle Dyer, Jackson McVey, Marcio Barbosa, Chris Padilla, Anthony Wint and Reinier de Ridder — fighters who finished their bouts without taking one of the $100,000 awards.<br><b>New at 12:38 — the payroll.</b> <b>Gregory Rodrigues led all fighters on the card with a $340,000 payday</b>: <b>$170,000 to show</b> and another <b>$170,000</b> as a win bonus, on top of the $100,000 Fight of the Night award (Yahoo Sports). <span style="color:var(--mut)">No other fighter\'s disclosed purse was stated in sources fetched this run, so no other figure is printed.</span>')

# 5 — UFC 331 card additions
rep(u'The co-main, <b>Arman Tsarukyan vs. Mauricio Ruffy</b> over five rounds, is billed as a <b>lightweight title eliminator</b>, with the winner expected to challenge champion Justin Gaethje next. Also booked: <b>Marlon Vera vs. Charles Jourdain</b>.',
    u'The co-main, <b>Arman Tsarukyan vs. Mauricio Ruffy</b> over five rounds, is billed as a <b>lightweight title eliminator</b>, with the winner expected to challenge champion Justin Gaethje next; coverage this run ranks <b>Tsarukyan No. 2</b> and <b>Ruffy No. 10</b> at lightweight. Also booked: <b>Marlon Vera vs. Charles Jourdain</b> and — <b>new at 12:38</b> — a lightweight rematch between <b>Renato Moicano</b>, a former UFC lightweight championship challenger, and <b>Brian Ortega</b>, a former UFC featherweight championship challenger.')

io.open(F,'w',encoding='utf-8').write(s); print("MMA OK")
