# -*- coding: utf-8 -*-
import io,sys
F='wallstreet-briefing.html'
s=io.open(F,encoding='utf-8').read()
def rep(old,new):
    global s
    n=s.count(old)
    assert n==1, "count=%d for %r" % (n, old[:90])
    s=s.replace(old,new)

# 1 — TLDR
rep(u'<div class="tldr"><b>The Tape</b> <span>Just past noon the tech-led rally has cooled a step — the latest read has the Dow up 147.67 points (+0.28%) and the Nasdaq Composite up 279.61 points (+1.07%), both below the 11:35 tallies, with the S&amp;P 500 still holding a 0.4% gain and Okta still the biggest single-stock mover.</span></div>',
    u'<div class="tldr"><b>The Tape</b> <span>The tech-led rally has re-accelerated into the afternoon — the latest read has the Nasdaq Composite up 400.29 points (+1.53%) and the Dow up 208.48 points (+0.39%), both above the 12:05 tallies, with the S&amp;P 500 still holding a 0.4% gain and Okta still the biggest single-stock mover.</span></div>')

# 2 — Lead tag + headline
rep(u'<span class="tag new">Updated · 12:05 PM ET</span><span class="tag acc">Midday session</span>\n<h3>Past noon the rally cools a step: the Dow and Nasdaq give back part of the midday gain — as of ~12:05 PM ET</h3>',
    u'<span class="tag new">Updated · 12:38 PM ET</span><span class="tag acc">Midday session</span>\n<h3>The rally re-accelerates after lunch: the Nasdaq Composite adds more than 400 points — as of ~12:38 PM ET</h3>')

# 3 — Lead para 1
rep(u'<p style="margin:0 0 10px">Just past noon, US stocks are still <b>climbing</b> after results from Nvidia, Salesforce and CrowdStrike lifted the technology trade — but the advance has <b>narrowed since late morning</b>. The latest read seen this run has the <b>Dow up 147.67 points, or 0.28%</b>, the <b>Nasdaq Composite up 279.61 points, or 1.07%</b>, and the <b>Russell 2000 up 7.64 points, or 0.25%</b>, with the <b>S&amp;P 500 holding a 0.4% gain</b>. <b>Both large-cap gauges are below the 11:35 tallies</b> this page carried — the Dow at +217.20 (+0.41%) and the Nasdaq at +327.22 (+1.25%) — so the direction is unchanged but the size of the move has come in. The page names that drift rather than quietly overwriting it.</p>',
    u'<p style="margin:0 0 10px">Into the early afternoon, US stocks are <b>climbing again</b> after results from Nvidia, Salesforce and CrowdStrike lifted the technology trade — and the advance has <b>widened back out since noon</b>. The latest read seen this run has the <b>Nasdaq Composite up 400.29 points, or 1.53%</b> and the <b>Dow up 208.48 points, or 0.39%</b>, with the <b>S&amp;P 500 still holding a 0.4% gain</b> (Yahoo Finance, Aug 27). <b>Both large-cap gauges are above the 12:05 tallies</b> this page carried — the Dow at +147.67 (+0.28%) and the Nasdaq at +279.61 (+1.07%) — so the cooling this page reported at midday has reversed, and the page names that reversal rather than quietly overwriting it. <b>No fresh Russell 2000 read was seen this run</b>, so the small-cap line from 12:05 (+7.64, +0.25%) is not restated as current.</p>')

# 4 — Lead para 2 (reconciliation + rejections)
rep(u'<b>Three index reads have now been taken across this session, and all three reconcile to the same prior close.</b> In order: <b>+169.90 (+0.32%)</b>, <b>+217.20 (+0.41%)</b> and now <b>+147.67 (+0.28%)</b> on the Dow, and <b>+300.97 (+1.15%)</b>, <b>+327.22 (+1.25%)</b> and now <b>+279.61 (+1.07%)</b> on the Nasdaq Composite. Each pair divides out to a prior close within the rounding band of Wednesday\'s, which is what makes them a sequence of intraday snapshots rather than competing claims about one moment — <b>so the newest leads and the earlier ones are kept as history, not averaged away</b>. <b>No source stamped its figures with a time</b>, so no level is asserted in this section; levels live in the Weekly Scorecard. <b>Two other items were rejected outright.</b>',
    u'<b>Four index reads have now been taken across this session, and all four reconcile to the same prior close.</b> In order: <b>+169.90 (+0.32%)</b>, <b>+217.20 (+0.41%)</b>, <b>+147.67 (+0.28%)</b> and now <b>+208.48 (+0.39%)</b> on the Dow, and <b>+300.97 (+1.15%)</b>, <b>+327.22 (+1.25%)</b>, <b>+279.61 (+1.07%)</b> and now <b>+400.29 (+1.53%)</b> on the Nasdaq Composite. Each pair divides out to a prior close within the rounding band of Wednesday\'s, which is what makes them a sequence of intraday snapshots rather than competing claims about one moment — <b>so the newest leads and the earlier ones are kept as history, not averaged away</b>. <b>No source stamped its figures with a time</b>, so no level is asserted in this section; levels live in the Weekly Scorecard. <b>Two other items were rejected outright.</b>')

# 5 — second aggregator rejection appended to the rejection paragraph
rep(u'because Nvidia reports its second quarter in the last week of August every year.</span></p>',
    u'because Nvidia reports its second quarter in the last week of August every year. <b>New at 12:38 — the same aggregator came back, and was rejected a second time.</b> It now says US markets <i>"ended the session slightly lower on August 27"</i> — a claim that is both impossible two and a half hours before the closing bell and the opposite direction to the close it asserted earlier today. <b>A source that dates a close before the close is not repaired by changing which way it went.</b> Not published.</span></p>')

# 6 — movers paragraph in the Lead
rep(u'<b>Salesforce is quoted at +11.2%</b> in the same coverage, against the <b>14.78%</b> carried at 9:35, and <b>CrowdStrike at +9.4%</b> against <b>14.34%</b> — a shade firmer than the 9% quoted at 11:35; the software pair have given back part of their opening pop, and every read is shown rather than the highest one being kept. <b>Nvidia</b> is described as up <b>6% to 7%</b>, the figures attached to its pre-market move rather than a fresh post-open quote, so the <b>5.87%</b> read carried at 9:35 remains the last live quote this page has for it. Names added to the board during the late morning: <b>Zscaler up 8.7%</b> and <b>Palantir up 3.8% at $184.32</b>. New at 12:05: <b>Arm Holdings up 6.2% at $266.50</b>. All three are morning-trading reads.</p>',
    u'<b>New at 12:38 — a fresh set of single-stock reads arrived with the fresh index set, and it is materially higher across the board.</b> The Yahoo Finance coverage carrying the +400.29 Nasdaq figure quotes <b>Nvidia up 9.48%</b>, <b>Salesforce up 21.04%</b> and <b>CrowdStrike up 17.93%</b>. Each is the highest read this page has seen for that name today, and each is printed as a read rather than adopted as the number: <b>Salesforce</b> has now been quoted at <b>14.78%</b> (9:35), <b>11.2%</b> (11:35 and 12:05) and <b>21.04%</b> (12:38); <b>CrowdStrike</b> at <b>8.9%</b> pre-open, <b>14.34%</b> (9:35), <b>9%</b> (11:35), <b>9.4%</b> (12:05) and <b>17.93%</b> (12:38); <b>Nvidia</b> at <b>5.87%</b> live just after the open, <b>6%–7%</b> in pre-market coverage and <b>9.48%</b> now. <span style="color:var(--mut)"><b>The Benzinga 11.2% / 9% pair resurfaced in a separate search this run and is not treated as a new competing read</b> — it is the same coverage this page already carried at 12:05, returning again. <b>None of these reads is averaged, and the spread is wide enough that this page asserts none of them as the move.</b></span> Names added to the board during the late morning and carried: <b>Zscaler up 8.7%</b>, <b>Palantir up 3.8% at $184.32</b> and <b>Arm Holdings up 6.2% at $266.50</b>.</p>')

# 7 — NVDA card
rep(u'<div class="card"><span class="tag">Carried</span><span class="tag acc">Semis</span>\n<h3>Nvidia (NVDA) — last live quote +5.87%, with coverage still citing the pre-market move</h3><p>The last live quote this page has for <b>NVDA is +5.87%</b>, taken just after the open. Coverage fetched this run still describes the stock as up <b>6%</b> to <b>7%</b>, but those figures are attached to <i>pre-market</i> trading in the same sentences, so they are not treated as a fresher post-open read. Every figure the page has carried is shown and none averaged: <b>7.4%</b> (Reuters/AOL), <b>7.32%</b> (Benzinga) and <b>6%</b> (CNBC) before the bell, "more than 4%" in Wednesday\'s extended session, and <b>5.87%</b> live.',
    u'<div class="card"><span class="tag new">Updated · 12:38</span><span class="tag acc">Semis</span>\n<h3>Nvidia (NVDA) — a fresh post-open read has it up 9.48%, its highest of the day</h3><p><b>New at 12:38:</b> Yahoo Finance\'s Aug 27 coverage — the same article carrying this run\'s index set — quotes <b>NVDA up 9.48%</b>. That is the first read this page has seen above the pre-market figures, and it replaces <b>5.87%</b> as the freshest quote here, though the earlier one is kept rather than erased. Every figure the page has carried is shown and none averaged: <b>7.4%</b> (Reuters/AOL), <b>7.32%</b> (Benzinga) and <b>6%</b> (CNBC) before the bell, "more than 4%" in Wednesday\'s extended session, <b>5.87%</b> live just after the open, and <b>9.48%</b> now.')

# 8 — CRM card
rep(u'<div class="card"><span class="tag">Carried</span><span class="tag acc">Software</span>\n<h3>Salesforce (CRM) — quoted at +11.2% at midday, off its opening pop</h3><p>The latest coverage seen this run has <b>CRM up 11.2%</b>, against the <b>14.78%</b> this page carried at 9:35 and the <b>nearly 12%</b> it showed in pre-market trade. All three reads are printed and none averaged.',
    u'<div class="card"><span class="tag new">Updated · 12:38</span><span class="tag acc">Software</span>\n<h3>Salesforce (CRM) — quoted at +21.04% in the afternoon, the widest read of the day</h3><p><b>New at 12:38:</b> the latest coverage seen this run has <b>CRM up 21.04%</b>, against <b>11.2%</b> at 11:35 and 12:05, <b>14.78%</b> at 9:35 and <b>nearly 12%</b> in pre-market trade. <b>All four reads are printed and none averaged</b> — the spread across them is roughly ten percentage points, so this page states the range and asserts no single figure. Separately, Seeking Alpha describes the shares as having "surged more than 10%" on the results, and Bloomberg lists Salesforce among the session\'s top performers on a strong revenue outlook and its deepened partnership with Anthropic.')

# 9 — CRWD card
rep(u'<div class="card"><span class="tag new">Updated · 12:05</span><span class="tag acc">Cybersecurity</span>\n<h3>CrowdStrike (CRWD) — quoted at +9.4% past noon, with a record ARR quarter</h3><p>The latest coverage seen this run has <b>CRWD up 9.4%</b>, a shade firmer than the <b>9%</b> quoted at 11:35 and well below the <b>14.34%</b> this page carried at 9:35; it showed <b>8.9%</b> pre-open. All four reads are printed and none averaged.',
    u'<div class="card"><span class="tag new">Updated · 12:38</span><span class="tag acc">Cybersecurity</span>\n<h3>CrowdStrike (CRWD) — quoted at +17.93% in the afternoon, with a record ARR quarter</h3><p><b>New at 12:38:</b> the latest coverage seen this run has <b>CRWD up 17.93%</b>, against <b>9.4%</b> at 12:05, <b>9%</b> at 11:35, <b>14.34%</b> at 9:35 and <b>8.9%</b> pre-open. <b>All five reads are printed and none averaged</b>, and the range is wide enough that no single figure is asserted here.')

# 10 — Chart of the Day note
rep(u'<div class="note">Okta is the session\'s single biggest mover on the latest tallies seen this run — <b>+26.17%</b> on one and <b>+19%</b> on another — so the chart tracks it. Nvidia set the tone with Wednesday evening\'s report, but it is no longer the largest move on the board.</div>',
    u'<div class="note">Okta is still the session\'s single biggest mover on the tallies seen this run — <b>+26.17%</b> on one and <b>+19%</b> on another — so the chart continues to track it. <b>Updated at 12:38:</b> Salesforce has closed much of the gap on a fresh read of <b>+21.04%</b>, which sits between Okta\'s two figures; the chart symbol is left on Okta because no read seen this run puts another name above 26.17%. Nvidia set the tone with Wednesday evening\'s report, but it is not the largest move on the board.</div>')

io.open(F,'w',encoding='utf-8').write(s)
print("WS OK")
