import sys
P='cyber-briefing.html'
h=open(P).read(); n=0
def rep(old,new,cnt=1):
    global h,n
    if old not in h: print("!! NOT FOUND:",old[:110]); sys.exit(1)
    h=h.replace(old,new,cnt); n+=1
h=h.replace('<span class="tag new">New &middot; 3:15</span>','<span class="tag">Carried &middot; 3:15</span>')

# TLDR
rep('<div class="tldr"><b>The Wire</b> <span>CISA\'s deadline to patch the maximum-severity Oracle WebLogic proxy flaw CVE-2026-21962 expires today, with the business day nearly over, and a second report has now put Saturday\'s Citrix NetScaler deadline on that flaw alone — contradicting the reporting this page has been carrying, which had Microsoft SQL Server sharing it.</span></div>',
 '<div class="tldr"><b>The Wire</b> <span>The federal deadline to patch the maximum-severity Oracle WebLogic proxy flaw CVE-2026-21962 has now run out, which moves Saturday\'s Citrix NetScaler deadline to the top of the board — and CISA\'s own alert page, dated August 26, settles the argument this page has been having about when that Citrix clock started.</span></div>')

# Top Story tags + expired framing
rep('<span class="tag">Carried · 12:38</span><span class="tag crit">Deadline today</span><span class="tag acc">KEV</span>\n<h3 style="margin:2px 0 8px;font-size:20px">Federal agencies have until today to patch a maximum-severity Oracle WebLogic proxy flaw</h3>',
 '<span class="tag new">Updated &middot; 4:05</span><span class="tag crit">Deadline expired</span><span class="tag acc">KEV</span><span class="tag">Carried &middot; 12:38</span>\n<h3 style="margin:2px 0 8px;font-size:20px">The federal deadline to patch a maximum-severity Oracle WebLogic proxy flaw has now expired</h3>\n<p style="margin:0 0 10px;padding:9px 12px;border-left:3px solid var(--crit);background:rgba(255,90,90,.06);border-radius:8px;font-size:14.3px"><b>New at 4:05 — the clock has run out.</b> The remediation date for <span class="mono">CVE-2026-21962</span> was <b>today, August 27</b>. As of this edition it is <b>past</b>, and the countdown below reads <b>overdue</b> rather than <i>0 days left</i>. <span style="color:var(--mut)">No source fetched this run reported a compliance figure, an extension, or any enforcement action, and none is invented. What changes on this page is the label on the clock, nothing more &mdash; but an unpatched maximum-severity flaw does not become less urgent for having missed its date, so the item stays at the top.</span></p>')

# Patch Priority rewrite
rep('<h3>Patch <span class="mono">CVE-2026-21962</span> — Oracle HTTP Server / WebLogic Server Proxy Plug-in — <span style="color:var(--crit)">due today, August 27</span></h3>',
 '<h3>Patch <span class="mono">CVE-2026-8452</span> — Citrix NetScaler ADC / Gateway — <span style="color:var(--crit)">due Saturday, August 29 — 2 days left</span></h3>\n<p style="margin:0 0 11px;font-size:14.4px"><b>New at 4:05 — the top of this box has changed, because a deadline expired.</b> <span class="mono">CVE-2026-8452</span> is now the most urgent item with a live federal clock: confirmed exploited in the wild for <b>remote code execution as root</b> (watchTowr), vendor-assigned <b>CVSS 8.8</b>, and due <b>Saturday, August 29</b>. Patch to <b>14.1-72.61 (FIPS)</b>, <b>13.1-63.18</b> or <b>13.1-37.272</b>. <b>New IOCs this run:</b> attackers were observed dropping web shells named <span class="mono">x.php</span> and <span class="mono">z.php</span> and running discovery commands including <span class="mono">id</span> and <span class="mono">echo</span> &mdash; <span style="color:var(--mut)">the first indicators of compromise this page has been able to publish for this flaw. Citrix disclosed it on <b>June 30, 2026</b>, with patches the same day, describing it only as a memory-overflow issue leading to unpredictable behaviour and denial of service; the RCE finding came later and from a third party. <b>Both framings stay on the page.</b></span></p>\n<p style="margin:0 0 11px;font-size:14.4px;color:var(--mut)"><b>The Oracle item below has not been removed &mdash; its deadline has passed.</b> It held this slot from the moment it was added until four o&rsquo;clock today.</p>\n<h3 style="opacity:.85">Then still patch <span class="mono">CVE-2026-21962</span> — Oracle HTTP Server / WebLogic Server Proxy Plug-in — <span style="color:var(--crit)">deadline expired August 27</span></h3>')

# KEV entries
rep('<li><b class="mono">CVE-2026-21962</b> — Oracle HTTP Server / WebLogic Server Proxy Plug-in. Added <b>Aug 24</b>, due <b>Aug 27</b> — <span style="color:var(--crit);font-weight:700" id="kev1">(0 days left)</span>.</li>',
 '<li><b class="mono">CVE-2026-21962</b> — Oracle HTTP Server / WebLogic Server Proxy Plug-in. Added <b>Aug 24</b>, due <b>Aug 27</b> — <span style="color:var(--crit);font-weight:700" id="kev1">(overdue — deadline expired today)</span>.</li>')
rep('<li><b class="mono">CVE-2026-60004</b> — Gitea remote code execution, fixed in 1.27.1. Due <b>Aug 28</b> — <span class="mono" id="kev2">(1 day left)</span>.</li>',
 '<li><b class="mono">CVE-2026-60004</b> — Gitea remote code execution, fixed in 1.27.1. Due <b>Aug 28</b> — <span style="color:var(--crit);font-weight:700" id="kev2">(1 day left — tomorrow)</span>.</li>')
rep('<li><b class="mono">CVE-2026-8452</b> — <b>new deadline verified this run.</b>',
 '<li><b class="mono">CVE-2026-8452</b> — <b>NOW THE TOP PRIORITY; start date settled at 4:05.</b> The CISA alert announcing the six-CVE batch is published at a URL dated <b>August 26</b>, and BleepingComputer&rsquo;s headline says feds must patch it <b>&ldquo;by Saturday&rdquo;</b> — Saturday being <b>Aug 29</b>. <span style="color:var(--mut)">One item fetched this run said the batch was added on <b>August 27</b>; the alert page&rsquo;s own date is preferred over a secondary summary, and the discrepancy is recorded rather than hidden. Either way the due date is unchanged.</span>')
rep('<li><b class="mono">CVE-2026-68820</b> — Windows AFD for WinSock zero-day. Due <b>Aug 25</b> — <span style="color:var(--crit);font-weight:700" id="kev3">(overdue)</span>.</li>',
 '<li><b class="mono">CVE-2026-68820</b> — Windows AFD for WinSock zero-day. Due <b>Aug 25</b> — <span style="color:var(--crit);font-weight:700" id="kev3">(overdue)</span>. <b>New at 4:05 — corroborated independently:</b> a use-after-free in <span class="mono">afd.sys</span> being exploited to <b>elevate privileges to SYSTEM</b>. <span style="color:var(--mut)">This is the first description of the flaw&rsquo;s mechanism this page has carried; the deadline is unchanged.</span></li>')

# Vulnerability Watch new rows
rep('<table><thead><tr><th>CVE</th><th>CVSS</th><th>Affected</th><th>Note</th></tr></thead><tbody>\n<tr><td class="mono">CVE-2026-45659</td>',
 '''<table><thead><tr><th>CVE</th><th>CVSS</th><th>Affected</th><th>Note</th></tr></thead><tbody>
<tr><td class="mono">CVE-2026-55040</td><td class="mono">Not confirmed this run</td><td>Microsoft SharePoint Server</td><td><b>New at 4:05.</b> Security-feature bypass reported as <b>exploited in the wild for ransomware</b>. <span style="color:var(--mut)">No CVSS, affected build or patch level was stated in the source fetched this run and none is borrowed. Note this is a <b>separate identifier</b> from the SharePoint deserialisation flaw CVE-2026-45659 already listed below; the two are not merged.</span></td></tr>
<tr><td class="mono">CVE-2026-33824</td><td class="mono">Not confirmed this run</td><td>Windows Internet Key Exchange Service Extensions</td><td><b>New at 4:05.</b> Remote code execution, reported as <b>exploited in the wild for ransomware</b>. <span style="color:var(--mut)">No CVSS was stated in the source fetched this run and none is printed; not among the KEV additions verified this run.</span></td></tr>
<tr><td class="mono">Not assigned this run</td><td class="mono">Not confirmed this run</td><td>VMware vCenter</td><td><b>New at 4:05.</b> A <b>China-nexus APT group</b> is reported to be exploiting a <b>newly patched</b> vCenter flaw to deploy <b>Babuk-derived ransomware</b>. <span style="color:var(--mut)"><b>No CVE identifier was stated in the reporting fetched this run, so this row carries none rather than guessing at one</b> — the row is published because the affected product and the actor class are stated, and it is labelled unidentified so a later run can attach the identifier when a source supplies it.</span></td></tr>
<tr><td class="mono">CVE-2026-45659</td>''')

open(P,'w').write(h); print("cyber edits applied:",n)
