# -*- coding: utf-8 -*-
import re, io
f='mma-briefing.html'
s=io.open(f,encoding='utf-8').read(); orig=len(s)
s=s.replace('<span class="tag new">New &middot; 12:24 PM</span>','<span class="tag">Carried &middot; Aug 31, 12:24 PM</span>')

new_tldr='<div class="tldr"><b>Tale of the Tape</b> <span><b>UFC Paris finally has a price, and it inverts the billing.</b> <b>Salahdine Parnasse is &minus;550 and Dan Hooker +400</b> for Saturday&rsquo;s five-round lightweight main event at the <b>Accor Arena</b> &mdash; <b>the promotion lists the veteran first and the books make the debutant a heavy favourite</b>. It is the <b>first refreshed price this page has been able to publish in several editions</b>. <b>Noche UFC joins the calendar</b> for <b>September 12 at Desert Diamond Arena in Glendale, Arizona</b>, the promotion&rsquo;s first event at that venue, with <b>Waldo Cortes-Acosta (No. 5) vs Curtis Blaydes (No. 7)</b> at heavyweight. <b>UFC Shanghai&rsquo;s bonus pool is settled at $400,000 across four $100,000 awards</b>, and this run&rsquo;s reporting <b>re-corroborates the right uppercut</b> as Song Yadong&rsquo;s finishing blow, resolving a dispute this page printed both sides of. <b>The champions board is unchanged for a seventy-fourth consecutive edition.</b></span></div>'
s=re.sub(r'<div class="tldr">.*?</div>',lambda m:new_tldr,s,count=1,flags=re.S)

# Top Story: new lead
top='''<div class="note lead" style="margin-bottom:14px"><span class="tag new">New &middot; 12:51 PM</span> <b>For the first time in several editions this page can print a betting price it fetched itself, and the price disagrees with the poster.</b> <b>UFC Fight Night: Hooker vs. Parnasse</b> &mdash; <b>UFC Fight Night 287</b>, <b>Saturday, September 5, at the Accor Arena in Paris</b> &mdash; is headlined by a <b>five-round lightweight bout</b> between <b>Dan Hooker</b> and <b>UFC newcomer Salahdine Parnasse</b>. The odds fetched this run: <b>Parnasse &minus;550, Hooker +400</b>. <b>The promotion bills Hooker first, as the veteran and the known name; the books have the debutant as better than a five-to-one favourite.</b> Both facts are printed because they are both true and the tension between them is the story of the card.<br><br>&#9888; <b>Why this matters beyond the number.</b> This page has spent multiple editions carrying odds lines with their books named and their dates receding, refusing to refresh them because <b>nothing fetched stated a current price</b>. <b>That refusal ends this run for this fight only</b> &mdash; every other odds line on this page below <b>remains carried at its original date and book</b>, and none of them is restated against this one.<br><br><b>The rest of the card filled in further.</b> Added this run: a welterweight bout between <b>former Bellator star Michael Page</b> and <b>Nursulton Ruziboev</b>; <b>French favourite Fares Ziam</b> against <b>Axel Sola</b> at lightweight; and, at featherweight, <b>Losene Keita vs Muhammad Naimov</b> alongside the <b>Morgan Charri&egrave;re vs Felipe Lima</b> bout already carried. <b>Punahele Soriano moving up to welterweight to face Daniil Donchenko</b> is re-confirmed. Broadcast is unchanged and re-confirmed: <b>prelims from noon ET, main card 3 p.m. ET, Paramount+</b>. &#9888; <b>Parnasse also appears on a roster tracker dated August 22 among recent signings</b>, which is consistent with &ldquo;newcomer&rdquo; and is the only corroboration of his status fetched this run.</div>'''
i=s.find('<h2 class="sec">Top Story</h2>')
s=s[:i+len('<h2 class="sec">Top Story</h2>')]+top+s[i+len('<h2 class="sec">Top Story</h2>'):]

# Upcoming cards: Noche UFC card
noche='''<div class="card"><span class="tag new">New &middot; 12:51 PM</span><p class="when">Sat, Sep 12, 2026 &middot; Desert Diamond Arena, Glendale, Arizona</p><h3>Noche UFC &mdash; Cortes-Acosta vs Blaydes</h3><p>The promotion returns to <b>Glendale, Arizona</b> for its <b>first event at Desert Diamond Arena</b>, marking <b>Mexican Independence Day</b>. Headlining at heavyweight: <b>No. 5 ranked Waldo Cortes-Acosta vs No. 7 ranked Curtis Blaydes</b> &mdash; a bout the promotion&rsquo;s own announcement frames as putting the winner closer to a title shot. Also scheduled: <b>Alexa Grasso vs Manon Fiorot</b> and <b>Brandon Moreno vs Joseph Morales</b>, with Grasso and Moreno described as <b>former UFC titleholders</b>. <b>Prelims 1 p.m. ET / 10 a.m. PT, main card 5 p.m. ET / 2 p.m. PT, Paramount+.</b> &#9888; <b>No odds published</b> &mdash; nothing fetched this run states a price for any bout on this card. &#9888; <b>Blaydes is not described here as a title challenger.</b> The report of his <b>new eight-fight contract</b>, which names this as his first bout under it, ran under a headline calling him an <b>&ldquo;ex-UFC title challenger&rdquo;</b>; <b>nothing fetched this run confirms he has fought for a UFC title</b>, and under this page&rsquo;s standing rule &mdash; the one written after Beneil Dariush was miscalled a challenger &mdash; <b>the descriptor is omitted rather than repeated</b>. The contract itself, and the September 12 date attached to it, are published.</p></div>'''
i=s.find('<h2 class="sec">Fight Week &mdash; Upcoming Cards</h2>')
if i<0: raise SystemExit('no fight week')
j=s.find('<div class="cards"',i); k=s.find('>',j)+1
s=s[:k]+noche+s[k:]

# Paris odds card note appended inside upcoming cards too -> add second card
paris='''<div class="card"><span class="tag new">New &middot; 12:51 PM</span><p class="when">Sat, Sep 5, 2026 &middot; Accor Arena, Paris</p><h3>UFC Fight Night 287 &mdash; Hooker vs Parnasse (odds refreshed)</h3><p>Five-round lightweight main event. <b>Odds: Salahdine Parnasse &minus;550 / Dan Hooker +400</b> (Yahoo Sports, fetched this run). Main card additions confirmed this run: <b>Michael Page vs Nursulton Ruziboev</b> (welterweight), <b>Fares Ziam vs Axel Sola</b> (lightweight), <b>Losene Keita vs Muhammad Naimov</b> and <b>Morgan Charri&egrave;re vs Felipe Lima</b> (featherweight), <b>Punahele Soriano vs Daniil Donchenko</b> (Soriano moving up to welterweight). <b>Prelims noon ET, main card 3 p.m. ET, Paramount+.</b></p></div>'''
s=s[:k]+paris+s[k:]

# Results section: bonuses + uppercut corroboration
res='''<p><span class="tag new">New &middot; 12:51 PM</span> <b>The Shanghai bonus pool is now settled, and it is bigger than a standard night.</b> Reporting fetched this run puts <b>$400,000 in total bonuses</b> across <b>four $100,000 awards</b>. <b>Song Yadong took Performance of the Night</b> for the main-event finish; <b>Bilal Hasan</b> took the other performance award; and <b>Liu Ce and Levi Rodrigues Jr. each received $100,000 for Fight of the Night</b>. &#9888; <b>Bilal Hasan is the same fighter who won a Contender Series contract on August 11</b> &mdash; eighteen days between a developmental contract and a six-figure bonus, stated here so it is not read as two people.<br><br>&#9888; <b>A dispute this page printed both sides of resolves toward the original reading.</b> At 11:50 this page recorded that its carried description of Song&rsquo;s finish &mdash; <b>a right uppercut as Umar Nurmagomedov shot for a takedown</b> &mdash; was in tension with reporting describing <b>a heavy right hand off the side of the head as he changed levels</b>. <b>A further account fetched this run describes it as a right uppercut that caught Nurmagomedov as he appeared to be shooting for a takedown, leaving him out cold before he hit the canvas.</b> <b>Two of three now say uppercut</b>, so the uppercut reading is the one carried; <b>the alternative is not deleted</b>, because a hand-shape disagreement between eyewitness write-ups is not settled by a show of hands. <b>Result, method, round and time are unaffected and unchanged: KO, round two, 1:48.</b></p>'''
i=s.find('<h2 class="sec">UFC Shanghai &mdash; Results</h2>')
if i<0: raise SystemExit('no results')
j=i+len('<h2 class="sec">UFC Shanghai &mdash; Results</h2>')
s=s[:j]+res+s[j:]

# Champions board note
ch='''<p class="note"><span class="tag new">New &middot; 12:51 PM</span> <b>Seventeenth cross-check, and the first in three runs to come back clean on every cell it reached.</b> An ESPN-sourced return this run matched this board on <b>seven cells with the fight, method, event and date attached to each</b>: <b>Aspinall</b> (June 21, 2025, inherited), <b>Ulberg</b> (KO1 over Ji&#345;&iacute; Proch&aacute;zka, UFC 327, April 11, 2026), <b>Strickland</b> (split decision over Khamzat Chimaev, UFC 328, May 9, 2026), <b>Makhachev</b> (unanimous decision over Jack Della Maddalena, UFC 322, November 15, 2025, <b>1 defence</b>), <b>Gaethje</b> (TKO4 over Ilia Topuria, UFC Freedom 250, June 14, 2026), <b>Volkanovski</b> (unanimous decision over Diego Lopes, UFC 314, April 12, 2025, <b>1 defence</b>) and <b>Yan</b> (reclaimed). <b>No conflation, no stale cache, no wrong names.</b> <b>Board unchanged &mdash; seventy-fourth consecutive edition.</b> &#9888; <b>The return did not reach flyweight or any women&rsquo;s division</b>; <b>Van, Harrison, Shevchenko and Dern are carried, not re-verified this run</b>, and the flyweight row continues to rest on <b>UFC 331&rsquo;s own billing of Van as current champion and Pantoja as former champion</b>.</p>'''
i=s.find('<h2 class="sec">Champions Board</h2>')
if i<0: raise SystemExit('no champs')
j=i+len('<h2 class="sec">Champions Board</h2>')
s=s[:j]+ch+s[j:]

src='<p><b>Sources checked this run &mdash; 12:51 PM:</b> <a href="https://www.ufc.com/event/ufc-fight-night-september-05-2026">UFC.com &mdash; UFC Fight Night: Hooker vs Parnasse (Paris)</a> &middot; <a href="https://sports.yahoo.com/articles/ufc-paris-watch-dan-hooker-125027816.html">Yahoo Sports &mdash; UFC Paris lineup and odds</a> &middot; <a href="https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/">MMAOddsBreaker &mdash; opening odds, UFC Paris</a> &middot; <a href="https://www.ufc.com/news/noche-ufc-take-place-september-12-ufc-returns-glendale-arizona">UFC.com &mdash; Noche UFC, September 12, Glendale</a> &middot; <a href="https://www.ufc.com/news/ufc-fight-night-shanghai-2026-bonus-coverage">UFC.com &mdash; UFC Shanghai bonus coverage</a> &middot; <a href="https://sports.yahoo.com/articles/ufc-fight-night-shanghai-results-140451896.html">Yahoo Sports &mdash; UFC Shanghai results and $400K in bonuses</a> &middot; <a href="https://www.espn.com/mma/story/_/id/14947566/current-all-ufc-champions">ESPN &mdash; current and all-time UFC champions</a> &middot; <a href="https://bloodyelbow.com/2026/08/21/ex-ufc-title-challenger-survives-trend-of-surprise-roster-removals-by-signing-new-8-fight-deal/">Bloody Elbow &mdash; new eight-fight deal (descriptor in headline not adopted)</a></p>'
m=re.search(r'<h2 class="sec"[^>]*>Sources</h2>',s) or re.search(r'<footer[^>]*>',s)
s=s[:m.end()]+src+s[m.end():]

io.open(f,'w',encoding='utf-8').write(s)
print('mma ok',orig,'->',len(s))
