# -*- coding: utf-8 -*-
"""Regenerate archive.html whole, from the snapshot files on disk. Never hand-curated."""
import io, os, re, sys, datetime
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from shared import css, masthead, nav, page

D = os.path.dirname(os.path.abspath(__file__))
AP = os.path.join(D, "archive")
SEC = [("cyber", "The Cyber Wire"), ("wallstreet", "The Closing Bell"), ("mma", "The Octagon")]

pat = re.compile(r'^(cyber|wallstreet|mma)-(\d{4})-(\d{2})-(\d{2})-(\d{4})\.html$')
snaps, unparsed = {}, []
for fn in sorted(os.listdir(AP)):
    if not fn.endswith(".html"):
        continue
    m = pat.match(fn)
    if not m:
        unparsed.append(fn); continue
    sec, y, mo, d, hhmm = m.groups()
    snaps.setdefault((int(y), int(mo), int(d)), {}).setdefault(hhmm, {})[sec] = fn

out, nlinks, neds = [], 0, 0
for dt in sorted(snaps, reverse=True):
    day = datetime.date(*dt)
    out.append('<h2 class="sec">%s</h2><div class="panel"><table><tr><th>Edition</th><th>Snapshots</th></tr>'
               % day.strftime("%B %-d, %Y"))
    for hhmm in sorted(snaps[dt], reverse=True):
        neds += 1
        h, mi = int(hhmm[:2]), int(hhmm[2:])
        label = "%d:%02d %s ET" % (h % 12 or 12, mi, "AM" if h < 12 else "PM")
        cells = []
        for sec, title in SEC:
            fn = snaps[dt][hhmm].get(sec)
            if fn:
                cells.append('<a href="archive/%s">%s</a>' % (fn, title)); nlinks += 1
            else:
                cells.append('<span class="mut">%s &mdash;</span>' % title)
        out.append('<tr><td>%s</td><td>%s</td></tr>' % (label, " &nbsp;&middot;&nbsp; ".join(cells)))
    out.append("</table></div>")

nfiles = sum(1 for f in os.listdir(AP) if f.endswith(".html"))
FOOT = ("<footer><h5>About the archive</h5><ul>"
        "<li>Snapshots are point-in-time: each file is frozen as published and is <b>not</b> updated afterwards, "
        "so figures inside an older snapshot may since have been corrected on the live pages.</li>"
        "<li>Live market widgets are deliberately absent from this index page.</li>"
        "<li>Snapshots older than 21 days are pruned automatically.</li></ul>"
        '<div class="disc">%d snapshots across %d editions and %d days.</div></footer>'
        % (nfiles, neds, len(snaps)))

EXTRA = ("footer h5{font-family:var(--mono);font-size:11.5px;letter-spacing:.2em;text-transform:uppercase;"
         "color:var(--accent);margin:34px 0 12px;padding-bottom:7px;border-bottom:1px solid var(--line)}"
         "footer ul{margin:0 0 14px;padding-left:19px;font-size:13.5px;color:var(--muted)}"
         "footer li{margin-bottom:7px}")
CSS = css("#8b93a1", "#c8cdd6", "#0b0c0e", "#141619", "#242830", EXTRA)

BODY = (masthead("Archive", "Point-in-time snapshots of every edition &mdash; regenerated by script each run")
        + '<div class="freshline" id="freshline">&nbsp;</div>'
        + nav("archive") + "".join(out) + FOOT)

html = page("Archive &mdash; Daily Briefings", CSS, BODY)
io.open(os.path.join(D, "archive.html"), "w", encoding="utf-8").write(html)
print("archive.html: %.1f KB | %d days | %d editions | %d links | %d files | %d unparsed"
      % (len(html) / 1024.0, len(snaps), neds, nlinks, nfiles, len(unparsed)))
assert not unparsed, unparsed
