#!/usr/bin/env python3
import io, sys

WS_SRC = '''<li><b>Post-close index prints, fetched this run</b> — two independent corroborating renderings of Monday&rsquo;s close: one giving S&amp;P 500 7,652.96 (&minus;21.41, &minus;0.28%), Dow 53,416.99 (+139.98, +0.26%) and Nasdaq Composite 25,980.19 (&minus;0.76%); the other giving S&amp;P 500 7,652.86 (&minus;0.28%), Dow 53,417.16 (+140.15, +0.26%) and Nasdaq Composite 25,980.19 (&minus;0.76%). Every figure in both reconciles exactly against Friday&rsquo;s verified closes. The Nasdaq level is asserted; the S&amp;P and Dow levels are shown as a pair. A third, earlier reading of S&amp;P &minus;0.24% / Dow +0.25% / Nasdaq &minus;0.55% is treated as late-session. — https://finance.yahoo.com/markets/stocks/articles/stock-market-today-aug-24-134834490.html</li>
<li>Reuters via The Spokesman-Review (Purvi Agarwal and Niket Nishant), &ldquo;Tech drags S&amp;P 500, Nasdaq lower as Iran tensions, Nvidia earnings loom,&rdquo; Aug 24 2026, updated 12:03 p.m. PT — fetched this run; source for the 11:55 a.m. ET reading (Dow +146.59/+0.28% to 53,423.60, S&amp;P 500 &minus;13.52/&minus;0.18% to 7,660.85, Nasdaq Composite &minus;99.04/&minus;0.38% to 26,081.41), the Philadelphia SE Semiconductor index &minus;2.64% to a three-week low, Nvidia &minus;2.03%, Micron &minus;5.76%, Broadcom &minus;1.74%, financials +1.19% with JPMorgan +1.49% and Visa +2.64%, Ford &minus;3.9%, GM &minus;1.9%, J.B. Hunt &minus;5.4%, the 50% Canadian auto tariff from January 1, NYSE decliners 1.14-to-1 and Nasdaq 1.38-to-1, S&amp;P 500 16 new highs / 6 new lows and Nasdaq 62 new highs / 70 new lows, the 30-year above 5%, one 25bp hike priced by end-2026 per LSEG, and the Richard Reyle (Questar Capital Partners) quotation — https://www.spokesman.com/stories/2026/aug/24/tech-drags-sp-500-nasdaq-lower-as-iran-tensions-nv/</li>
<li>24/7 Wall St. (David Moadel), &ldquo;Memory Stocks Slide on Report Apple May Source Chinese Chips,&rdquo; published Aug 24 11:29 a.m. EDT — fetched this run; source for SanDisk &minus;9% at $1,458.29, Micron &minus;7% at $897.86, Western Digital &minus;7% at $429.49, SK hynix &minus;5% at $154.48, Roundhill Memory ETF &minus;7% at $53.62, the CXMT/YMTC sourcing report and the ~September 24 Xi visit window, SanDisk +572% and Micron +239% year to date through Friday&rsquo;s close, the KC Rajkumar (Lynx Equity Research) qualification and yield findings, the Section 1260H listing, the August 17 Lutnick remark, and the losers/gainers board (Coterra &minus;8.62%, Micron &minus;6.97%, Seagate &minus;6.79%, J.B. Hunt &minus;6.55%, Western Digital &minus;6.45%; Expedia +4.45%, Altria +3.98%, Verisign +3.40%, GoDaddy +3.03%) — https://247wallst.com/investing/2026/08/24/memory-stocks-slide-on-report-apple-may-source-chinese-chips-sandisk-down-9-micron-and-western-digital-down-7/</li>
<li>StockAnalysis.com after-hours movers (4:00&ndash;8:00 p.m. ET) — fetched this run and found <b>NOT YET ROLLED OVER</b>: heading read &ldquo;Stock Indexes &mdash; Aug 21, 2026 &mdash; After-hours&rdquo; with both tables stamped &ldquo;Updated Aug 21, 2026.&rdquo; No after-hours figure is published from it. — https://stockanalysis.com/markets/afterhours/</li>
<li>Stock Market Watch late-session sector board — consumer staples +1.30%, communication services +0.99%, financials +0.96%, technology &minus;1.47% (semiconductors &minus;2.23%), energy &minus;1.00% as worst sector; alongside Dow +0.13%, S&amp;P 500 &minus;0.26%, Nasdaq Composite &minus;0.77%. <b>Treated as frozen</b> after repeating byte-identical tables across several runs, so read as a late-session snapshot, not a certified close. — https://stockmarketwatch.com/live/stock-market-today</li>
<li>Yahoo Finance live blog (Grace O&rsquo;Donnell), fetched this run and <b>CACHED for an eighth time</b>: strip read &ldquo;U.S. markets open in 5h 6m&rdquo; (open anchor: 9:30 &minus; 5h06m = <b>4:24 a.m. ET</b>), carrying pre-open futures and a trending rail still showing Friday&rsquo;s Alibaba &minus;8.57%. Nothing published from it. — https://finance.yahoo.com/markets/live/stock-market-today-monday-august-24-dow-sp-500-nasdaq-080306047.html</li>
'''

CY_SRC = '''<li>CVE Brief daily security brief, edition dated <b>Sunday, August 23, 2026</b> (covering August 22 disclosures) — fetched this run; source for the Fabrik extension for Joomla cluster (CVE-2026-76604, CVE-2026-76605, CVE-2026-76606 and CVE-2026-76607 at CVSS 10.0; CVE-2026-77992 at 9.5; CVE-2026-76571 and CVE-2026-76602 at 9.3; CVE-2026-76596/76597/76598/76599 at 8.7 and CVE-2026-77027 at 8.6), for &ldquo;six of the 12 critical CVEs&rdquo; and &ldquo;12 critical CVEs, down 45% from 22 the prior day; 84 high-priority,&rdquo; for 0% patch availability at collection time, and for TRENDnet TEW-821DAP CVE-2026-77946 (10.0), CVE-2026-77945 (7.4), Comfast CF-N1-S CVE-2026-78050 (9.9) and Google Cloud Application Integration CVE-2026-12710 (9.3). <b>Caution recorded:</b> this source renders every KEV entry at a flat &ldquo;9.5&rdquo;, which conflicts with vendor scores verified elsewhere on this page (Zimbra CVE-2026-73570 is CVSS 8.9), so <b>no CVSS figure for a KEV entry is taken from it</b> — https://cvebrief.com/</li>
<li>Help Net Security (Sinisa Markovic), &ldquo;Critical Microsoft Entra ID vulnerability&hellip; (CVE-2026-69836),&rdquo; Aug 21 2026 — fetched this run; source for CVSS 10.0, deserialization of untrusted data enabling unauthenticated remote code execution, discovery credited to Microsoft Principal Security Engineer Robert Fitzpatrick, and Microsoft&rsquo;s statement that the issue is fully mitigated with no customer action required — https://www.helpnetsecurity.com/2026/08/21/microsoft-entra-id-vulnerability-cve-2026-69836/</li>
<li>The Hacker News front page, fetched this run — re-confirms the Aug 24 items already carried here (Keycloak CVE-2026-18963 at CVSS 9.1, fixed in 26.7.2 / RHBK 26.4.15 and 26.6.6, no evidence of exploitation as of Aug 24; UAT-10147 and SPECTRE; the Akamai enterprise AI findings; Operation QUICSILVER) and carries the correction on CVE-2026-69836: Microsoft changed the &ldquo;Exploited&rdquo; field from &ldquo;Yes&rdquo; to &ldquo;No&rdquo; on <b>August 21, 2026</b> after The Hacker News contacted the company, stating the flaw &ldquo;was not exploited in the wild.&rdquo; <b>A search summary this run misdated that reversal to August 24; the August 21 date is the one published here.</b> — https://thehackernews.com/2026/08/microsoft-entra-id-flaw-cvss-100.html</li>
<li>CISA — Known Exploited Vulnerabilities catalog and alert pages. A dedicated check this run for KEV additions dated <b>August 22&ndash;24 returned none</b>; the Aug 21 Zimbra entry (CVE-2026-73570) remains the newest, and the most recent CISA alert page remains Aug 20 (TrueConf &times;2), behind Aug 18 &times;4 and Aug 11 &times;3 — https://www.cisa.gov/known-exploited-vulnerabilities-catalog</li>
'''

for path, block in (('wallstreet-briefing.html', WS_SRC), ('cyber-briefing.html', CY_SRC)):
    h = io.open(path, encoding='utf-8').read()
    anchor = '<div class="lab">Sources</div>\n<ul>\n'
    if anchor not in h:
        print('MISS anchor in', path); sys.exit(1)
    h = h.replace(anchor, anchor + block, 1)
    io.open(path, 'w', encoding='utf-8').write(h)
    print('  ok sources ->', path)
print('DONE')
