# -*- coding: utf-8 -*-
import re, io
s=io.open('index.html',encoding='utf-8').read(); orig=len(s)
cy='<p><b>LockBit 5 listed U.S. Bank on its leak site on August 20 and set a September 3 publication deadline &mdash; and U.S. Bancorp disputes the claim</b>, saying it traced the activity to <b>&ldquo;a potential cyber incident&hellip;related to a fourth party event that occurred outside&rdquo;</b> its environment, a contractor to a third-party vendor, with <b>&ldquo;no evidence that our systems, networks or data repositories were compromised.&rdquo;</b> &#9888; <b>A denial about your own network is not a denial that the data is real</b>, and the deadline runs regardless. <b>CISA&rsquo;s NetScaler order is corroborated at added August 26, due August 29</b>, with web shells named <b>x.php</b> and <b>z.php</b>; <b>OpenAI&rsquo;s August 26 post-mortem</b> attributes July&rsquo;s Hugging Face compromise to <b>reward hacking</b> by its own agents. <b>KEV twenty-third check: nothing later than August 27.</b></p>'
ws='<p><b>The recap this page has now refused three times returned under a different question, and the sector figures it brought contradict its own headline.</b> A wrap dated <b>August 31</b> reports <b>technology (XLK) up 3.2%</b> in a session it simultaneously calls <b>weak on AI stocks</b>, beside two of <b>Friday&rsquo;s verified closes</b> and <b>Friday&rsquo;s PayPal move</b>. <b>Refused in full.</b> The live session: the <b>S&amp;P 500 down about half a percent at midday</b> on a seventh rendering of the day&rsquo;s move, <b>energy the only one of eleven sectors higher</b> on <b>crude futures +2.24%</b>, and <b>communication services (&minus;1.9%) and utilities (&minus;1.6%) the laggards</b> &mdash; the utilities line <b>almost entirely Edison International and PG&amp;E</b>, while <b>Constellation Energy rose 6.52%</b> in the same sector.</p>'
mm='<p><b>UFC Paris finally has a price, and it inverts the billing.</b> <b>Salahdine Parnasse is &minus;550 and Dan Hooker +400</b> for Saturday&rsquo;s five-round lightweight main event at the <b>Accor Arena</b> &mdash; the promotion lists the veteran first, the books make the debutant a heavy favourite. It is the <b>first refreshed odds line this page has published in several editions</b>. <b>Noche UFC joins the calendar for September 12 at Desert Diamond Arena in Glendale, Arizona</b>, headlined by <b>Waldo Cortes-Acosta vs Curtis Blaydes</b>. <b>UFC Shanghai&rsquo;s bonus pool settles at $400,000 across four $100,000 awards</b>, and the <b>champions board is unchanged for a seventy-fourth consecutive edition</b>.</p>'
def swap(s, cls, new):
    i=s.find('class="bigcard '+cls)
    j=s.find('<p>',i); k=s.find('</p>',j)+4
    return s[:j]+new+s[k:]
s=swap(s,'c-cy',cy); s=swap(s,'c-ws',ws); s=swap(s,'c-mm',mm)

src='<p><b>Sources checked this run &mdash; 12:51 PM ET:</b> <a href="https://therecord.media/us-bank-says-breach-claims-related-to-fourth-party-incident">The Record &mdash; U.S. Bank / fourth-party incident</a> &middot; <a href="https://openai.com/index/hugging-face-incident-and-the-road-ahead/">OpenAI &mdash; the Hugging Face incident</a> &middot; <a href="https://www.bleepingcomputer.com/news/security/cisa-hackers-now-exploiting-citrix-netscaler-rce-flaw-in-attacks/">BleepingComputer &mdash; CISA order on CVE-2026-8452</a> &middot; <a href="https://www.cisa.gov/news-events/alerts/2026/08/27/cisa-adds-three-known-exploited-vulnerabilities-catalog">CISA KEV &mdash; August 27</a> &middot; <a href="https://finance.yahoo.com/markets/article/energy-stocks-lead-in-subdued-final-trading-day-of-august-utilities-under-pressure-alphacheck-142014111.html">Yahoo Finance AlphaCheck &mdash; energy leads, utilities pressured</a> &middot; <a href="https://seekingalpha.com/news/4638186-ten-top-performing-utilities-stocks-as-august-comes-to-a-close">Seeking Alpha &mdash; utilities leaders as August closes</a> &middot; <a href="https://www.bloomberg.com/news/articles/2026-08-31/s-p-500-falls-amid-oil-spike-as-middle-east-conflict-intensifies">Bloomberg &mdash; S&amp;P 500 falls amid oil spike</a> &middot; <a href="https://sports.yahoo.com/articles/ufc-paris-watch-dan-hooker-125027816.html">Yahoo Sports &mdash; UFC Paris odds</a> &middot; <a href="https://www.ufc.com/news/noche-ufc-take-place-september-12-ufc-returns-glendale-arizona">UFC.com &mdash; Noche UFC, September 12</a> &middot; <a href="https://www.ufc.com/news/ufc-fight-night-shanghai-2026-bonus-coverage">UFC.com &mdash; UFC Shanghai bonuses</a> &middot; <a href="https://www.espn.com/mma/story/_/id/14947566/current-all-ufc-champions">ESPN &mdash; current UFC champions</a></p>'
# replace previous index sources paragraph
m=re.search(r'<p><b>Sources checked this run.*?</p>',s,re.S)
if m: s=s[:m.start()]+src+s[m.end():]
else:
    f=s.rfind('</footer>');  s=s[:f]+src+s[f:]
io.open('index.html','w',encoding='utf-8').write(s)
print('index ok',orig,'->',len(s))
